### ISSUE TITLE
AWS prelim worlds

### ISSUE THREAD

**Issue by meryl-spencer** [osrf/subt#1000]
Can we get the prelim worlds available for testing on AWS.

**Comment by meryl-spencer** [comment]
It looks like the worlds are up now but I get the following error when using the rest api
{"errcode":3013,"msg":"Invalid value in field.","extra":["Circuit:Finals Preliminary Round World 3"],"errid":"c6f5a613-3f71-47c4-9de0-b1fef99a7914","route":"POST /1.0/simulations","user-agent":"curl/7.58.0","remote-address":"35.63.66.108"}

**Comment by meryl-spencer** [comment]
The error also appears when using the web interface

**Comment by m3d** [comment]
ACK, I see the same
```
"errcode": 3013,
    "msg": "Invalid value in field.",
    "extra": [
        "Circuit:Finals Preliminary Round World 1"
    ],
```

**Comment by nkoenig** [comment]
Can you please try again. The worlds should be available for practice.

**Comment by m3d** [comment]
It works for me, thanks! (`99ecb8fc-f420-42ea-8043-b8a3c4072d37`)
