### ISSUE TITLE
REST API for final worlds?

### ISSUE THREAD

**Issue by m3d** [osrf/subt#1013]
What are the names for the final worlds please? I can run it directly on CloudSim, but REST API refuses guessed `Final Prize Round World 8`. Thanks m.
p.s. I do not see them listed even on
https://pkg.go.dev/gitlab.com/ignitionrobotics/web/cloudsim/simulations
so maybe they are not available yet??

**Comment by wolfgangschwab** [comment]
Hi Martin, 
you need to add an "s" at the end of Final.
This works for me:
'Final**s** Prize Round World 8'

**Comment by m3d** [comment]
Hi Wolfgang,
that worked, thanks!
