### ISSUE TITLE
Any tutorial to create custom world for unit testing?

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#109]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/109)) by baila (Bitbucket: [baila](https://bitbucket.org/%7B22c52b82-0467-49e5-afbf-803525a87d06%7D/)).**

----------------------------------------
Hi All,

Is there any tutorial page available describing the steps to build custom world as per need? e.g. if I want to test only an intersection path and nothing else, it would be very helpful just to add the staging area and one junction with it and do the test. No need to load those big world maps and all.

‌

Please redirect to such link or provide steps.

**Comment by nkoenig** [comment]
A [world creation](https://github.com/osrf/subt/wiki/World-Creation-Tutorial) tutorial is available.
