### ISSUE TITLE
Indication when all ignition processes are launched

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#145]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/145)) by Derek Knowles (Bitbucket: [dknowles-ssci](https://bitbucket.org/%7B85065c1d-731c-4c25-85e3-d2b87c9fed26%7D/)).**

----------------------------------------
I’d like to second a proposal that @Zbyněk Winkler made in issue #95 to create an indicator when all ignition processes have been successfully launched.

I'm running in a catkin workspace and I've noticed that there's a time between when the terminal where I run `ign launch -v 4 tunnel_circuit_practice.ign worldName:=tunnel_circuit_practice_01` stops printing outputs and when it’s safe to launch our controller.

Some kind of indication when all ignition processes have launched and it’s safe to launch our controller would be helpful.

**Comment by nkoenig** [comment]
All robots are spawned during the same simulation step since the Urban Circuit. Your solution can monitor robot topics, and the clock topic.
