### ISSUE TITLE
Vehicles with multiple mobility modes

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#15]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/15)) by Neil Johnson (Bitbucket: [realdealneil1980](https://bitbucket.org/%7Bace5bb77-1f3f-47ce-ad95-ea205b690930%7D/)).**

----------------------------------------
SSCI proposed using vehicles with multiple mobility modes (i.e. vehicles that can travel on ground and in the air).  Will such vehicles be added to the available models?  If so, we'd like to request that that be done fairly soon so that we can start using them in our simulations.

**Comment by nkoenig** [comment]
[Marsupial robot configurations](https://github.com/osrf/subt/wiki/Marsupial-tutorial) are available, which support both ground and air vehicles.
