### ISSUE TITLE
Expected X2 acceleration?

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#166]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/166)) by Martin Dlouhy (Bitbucket: [robotikacz](https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/)).**

----------------------------------------
What is maximal expected X2 acceleration? According to

[https://github.com/osrf/subt/blob/master/x2\_control/config/control.yaml](https://github.com/osrf/subt/blob/master/x2_control/config/control.yaml)

it should be

has\_acceleration\_limits: true  
max\_acceleration       : 7.0   # m/s^2

But when I run simulation last night it triggered \(with the latest docker image\) several false “collision detection” due to acceleration magnitude \(after G-force removal\) larger than 14m/s^2??

`acc [-49, -4, 9816]`  
`acc [10522, -3, 11376]`  
`acc [4278, -18, 7706]`  
`acc [4320, -40, 7673]`  
`acc [14022, -37, 12505]`  
`0:00:00.836728 Collision! [14.022, -0.037, 12.505] reported: False`  
`acc [9779, 10, 9818]`

I can move the threshold, so it just note, that X2 behavior changed.

**Comment by nkoenig** [comment]
Are you still experiencing this issue?

**Comment by nkoenig** [comment]
Closing due to lack of response.
