### ISSUE TITLE
Issues while following instructions for Docker installation

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#171]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/171)) by Anonymous.**

----------------------------------------
I recently tried redoing the Docker installation, which is here:

https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/wiki/tutorials/SystemSetupDockerInstall

I had two problems in conjunction with this: 
1) When I run step 2, it had me install "nvidia-384" which includes an outdated version of the nvidia drivers for my graphics card that breaks when I run code that uses CUDA (such as yolo).  
2) After following all instructions, docker was not installed...I thought it might get installed as part of the nvidia-container-toolkit installation, but it was not.  I had to install docker.io manually.  

Everything is now working for me after reinstalling my graphics driver (which took a bit of work that I don't want to describe fully here, but was pretty painful) and installing docker.io.  I am putting this here mostly in hopes that it will help others and possibly cause the wiki page to reflect these issues.

**Comment by nkoenig** [comment]
Updated docker instructions are [here](https://github.com/osrf/subt/wiki/Docker-Install) along with a note in the Nvidia section to first install docker.
