### ISSUE TITLE
Error "Problem registering with broker"

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#178]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/178)) by Sophisticated Engineering (Bitbucket: [sopheng](https://bitbucket.org/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D/)).**

----------------------------------------
I downloaded a new Docker image and now I get errors \(which have already also been mentioned in the resolved issue #168\).

Running the docker with only one robot with:

`./run.bash osrf/subt-virtual-testbed tunnel_circuit_practice.ign robotName1:=X3_TB robotConfig1:=X3_SENSOR_CONFIG_1`

and then starting our nodes, I get many errors like:

> \[X3\_TB\] CommsClient::Register: Problem registering with broker  
> \[CommsClient\] Retrying register..  
> \[X3\_TB\] CommsClient::Register: Problem registering with broker  
> \[CommsClient\] Retrying register..  
> \[X3\_TB\] CommsClient::Register: Problem registering with broker  
> \[CommsClient\] Retrying register..  
> \[X3\_TB\] CommsClient::Register: Problem registering with broker  
> \[CommsClient\] Retrying register..

Using an 4 day old image with 

`./run.bash a28b5c00f6ab tunnel_circuit_practice.ign robotName1:=X3_TB robotConfig1:=X3_SENSOR_CONFIG_1`

no errors occur when starting our nodes.

**Comment by plumewind** [comment]
Hello ， I also meet the same problem：

[staging_area] CommsClient::Register: Problem registering with broker
[CommsClient] Retrying regster..
[staging_area] CommsClient::Register: Problem registering with broker
[CommsClient] Retrying regster..
[staging_area] CommsClient::Register: Problem registering with broker
[CommsClient] Retrying regster..
[staging_area] CommsClient::Register: Problem registering with broker

Is the source code update ? I want to use it in Catkin System. Thanks a lot
