### ISSUE TITLE
[Urban Feature] Camera coordinate frame changed from gazebo9 to ignition

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#184]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/184)) by Neil Johnson (Bitbucket: [realdealneil1980](https://bitbucket.org/%7Bace5bb77-1f3f-47ce-ad95-ea205b690930%7D/)).**

----------------------------------------
It appears that the orientation of the camera coordinate frame is different in the ignition simulator than in the gazebo 9 simulator.  This has had undesirable consequences with some of our object localization math and visual odometry methods.  

In gazebo 9, the camera frame \(according to tf\) was oriented with x right, y down, z out the optical axis of the camera.   This lined up with our expectations.  In ignition, the camera frame is oriented x out the optical axis, y left, and z up.  So, it is basically the same as the body frame axes translated to the base of the camera.  

I don’t particularly want things to change at this point, but I’d like it if someone could confirm that indeed the coordinate frame changed during the migration to ignition, and to make the teams aware of this change in case it affects them too.

**Comment by nkoenig** [comment]
[Optical frames](https://github.com/osrf/subt/pull/413) have been added.
