### ISSUE TITLE
Expected NVIDIA driver compatability

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#191]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/191)) by Reid Sawtell (Bitbucket: [rsawtell](https://bitbucket.org/%7B845ed98c-79aa-4771-ab0d-6d8424f27344%7D/)).**

----------------------------------------
NVIDIA CUDA version compatibility in docker is dependent on host OS  NVIDIA driver version. What should we expect as the minimum NVIDIA driver version we will encounter in the competition amazon cloudsim environment?

**Comment by zwn** [comment]
> In a nutshell:
> 
> ```
> Driver Version: 418.40.04
> CUDA Version: 10.1
> ```

Is this still true? I was not able to find anywhere the driver version used on cloudsim. Can this information be added to the wiki?
