### ISSUE TITLE
AWS cloudsim_sim version?

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#193]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/193)) by Martin Dlouhy (Bitbucket: [robotikacz](https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/)).**

----------------------------------------
What is the current `cloudsim_sim` version on Amazon? I am still fighting with artifact report \(#186\) but then I realized that `osrf/subt-virtual-testbed:cloudsim_sim_latest` is older release\(?\) and I have still \(or again\) problem with IMU update \(#172\). Can you confirm that the same version which is available for download is also running on AWS?

`0:05:00.007580 (10.3 13.4 0.0) [('acc', 8160), ('pose2d', 1634), ('rot', 8160), ('scan', 327), ('sim_time_sec', 33)]` so IMU has 250Hz update …

thank you

Martin

**Comment by nkoenig** [comment]
Docker image versions are present on the [release notes](https://github.com/osrf/subt/wiki/release_notes). These are the same versions that are run on cloudsim up until a circuit event. During a circuit event, a new image with private competition worlds will be used.
