### ISSUE TITLE
Duplicate Artifact Report Documentation Inconsistencies

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#203]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/203)) by Cameron Ridgewell (Bitbucket: [cridgewell](https://bitbucket.org/%7B2511fb26-8278-48bf-8579-8132f927a689%7D/)).**

----------------------------------------
In reference to [Issue #196](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/196/update-qual_cloudsim-instructions) (#196), there is an inconsistency in the documentation for the scoring behavior.

‌

According to Section 11.3 of the [SubT Challenge Tunnel Circuit Rules Document](https://www.subtchallenge.com/resources/SubT_Challenge_Tunnel_Rules.pdf):

_For the Tunnel Circuit, the total number of artifacts is 20 and the total number of allowed scored reports is 40. Once an artifact has been successfully reported, any duplicate reports will be considered invalid and will count against the total number of reports._

But according to the [API Documentation](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/wiki/api):

_Repeated artifact requests \(a request is considered repeated when contains the same artifact type and position as a previously sent request\) do not count as new requests for scoring purposes. In other words, a team will not lose an extra token while retrying to send a previously reported artifact._

**Comment by angelacmaio** [comment]
Resolved. The API matches the [Cave Circuit Rules](https://www.subtchallenge.com/resources/SubT_Challenge_Cave_Rules.pdf). Exact duplicate reports are not scored in the Virtual Competition.
