### ISSUE TITLE
Ignition Clock Randomly Freezes

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#221]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/221)) by Reid Sawtell (Bitbucket: [rsawtell](https://bitbucket.org/%7B845ed98c-79aa-4771-ab0d-6d8424f27344%7D/)).**

----------------------------------------
Ignition seems to be experiencing some sort of freeze event where the clock randomly stops publishing for upwards of 20 seconds or more at a time. I’ve tested this with local catkin and local cloudsim in simple\_tunnel\_02 and both experience it. It may happen right at the start, or after it’s been running for a period of time, or not at all.

A snippet of the clock output via “rostopic echo /clock”:  

> clock:  
> secs: 89  
> nsecs: 504000000
>
> clock:  
> secs: 89  
> nsecs: 508000000
>
> clock:  
> secs: 89  
> nsecs: 512000000
>
> clock:  
> secs: 165  
> nsecs: 928000000
>
> clock:  
> secs: 165  
> nsecs: 932000000
>
> clock:  
> secs: 165  
> nsecs: 936000000

I’m not seeing any error messages from the ignition or bridge consoles, the SubT Simulator window is still responsive, but the realtime factor doesn’t change for the duration of the freeze \(normally it’s constantly changing\).  All of our solution nodes stop responding as well, without error, until the clock starts again after which we get a lot of errors related to time jumping into the future. If I run long enough, it may happen multiple times.

‌

**Comment by nkoenig** [comment]
The clock can stop (along with all of simulation) while new levels are loaded or unloaded. This is expected behavior. Please re-open if you notice some different behavior.
