### ISSUE TITLE
[Urban Feature] Add a bit more information to the simulation summary email

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#223]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/223)) by GoRobotGo (Bitbucket: [GoRobotGo](https://bitbucket.org/%7B2fd8dac8-286d-461a-b7dd-dba99deea025%7D/)).**

----------------------------------------
In addition to the current information in the simulation summary email it would be nice to have the score, the vehicle types and the docker urls used.

**Comment by peci1** [comment]
This issue can be closed? See #627.
