### ISSUE TITLE
Odometry of robots X1 vs. X2

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#243]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/243)) by Martin Dlouhy (Bitbucket: [robotikacz](https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/)).**

----------------------------------------
Is it expected that odometry for robot X2 is double when compared to X1? “Just for fun” we tried to run navigation code for X1 instead of X2 robot and it turned always half of desired angle … so X2 turned 90 degrees and X1 only 45, but the angles from odometry were the same. If there is a bug, please do not fix it now! :wink:

Is there any other team using X1 and X2?

**Comment by nkoenig** [comment]
Are you still seeing this issue?
