### ISSUE TITLE
Cloudsim simulation problems

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#246]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/246)) by GoRobotGo (Bitbucket: [GoRobotGo](https://bitbucket.org/%7B2fd8dac8-286d-461a-b7dd-dba99deea025%7D/)).**

----------------------------------------
The data for this run can be see in the try15c run.  The issues seen:

1.  Cloudsim did not respond to vehicle commands for 20 seconds.  Vehicle turn was commanded at sim time 67, but did not start turning until sim time 84.
2. Cloudsim did not provide consistent imu data until sim time 299.  It looks like one message came through early and no more imu messages until time 299.
3. Cloudsim imu data dropped out at time 362 and no futher imu data was available for the run.
4. Ground truth data dropped out intermittently while in the start area  - 873 to 907 for example

These were the issues for the first vehicle.  It looks like when there are multiple vehicles there is a high probability of maybe ignition bridge problems.

‌

**Comment by nkoenig** [comment]
Closing in order to triage the issue tracker.
