### ISSUE TITLE
Add version numbers to docker images allowing for regression testing

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#256]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/256)) by Zbyněk Winkler (Bitbucket: [Zbyněk Winkler (robotika)](https://bitbucket.org/%7Bd253a02a-aa23-4c28-9bf2-75863acb0ee0%7D/)).**

----------------------------------------
At docker hub, the images should have version numbers and each and every published image should be available to download to allow for regression testing \(something works with one version and does not work with other\).

In addition, it would be best if the cloud environment allowed selecting an explicit version of the docker images to run against. Again this will help tremendously to debug what is wrong, which in turn will help us create a more specific issues here that can be actionable instead of just saying “it does not work”.

This is a followup to [https://community.subtchallenge.com/t/cloudsim-version-numbering-and-staging-releases/1147](https://community.subtchallenge.com/t/cloudsim-version-numbering-and-staging-releases/1147) where Tim Chung stated during the Virtual Tunnel award ceremony, that is should be implemented.

**Comment by nkoenig** [comment]
Version numbers have been added to the release notes.

We don't plan on supporting different docker images on Cloudsim.
