### ISSUE TITLE
Ignition GUI: Links in the image selection dropdown menu are mixed up

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#278]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/278)) by Sophisticated Engineering (Bitbucket: [sopheng](https://bitbucket.org/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D/)).**

----------------------------------------
The image display in the ignition GUI has a minor bug in the dropdown menu. The dropdown menu shows a list of all available image topics. The names in the list do not correspond to the shown image topics. It seems that they are shifted to the next menu item.

Additional question \(or enhancement request\): is there an option to save an image shown in the image display to the harddisk? This would be helpful in some cases.

**Comment by nkoenig** [comment]
The image viewer displays correct images using Ignition Dome. Please re-open this issue if the problem persists.
