### ISSUE TITLE
Future enhancement: Droppable communications repeater nodes

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#279]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/279)) by Malcolm Stagg (Bitbucket: [malcolmst7](https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/)).**

----------------------------------------
As a future enhancement \(not necessarily for Urban Circuit since this is probably a larger change\), I would like to suggest we have robots capable of carrying dropping nodes, where each node is capable of relaying messages and similar communications-related functionality. This is a capability which would be possible in the real world, so it would be nice to enable it for the virtual track as well. 

These communications nodes could potentially help extend communications distances and store information \(warning messages, mapping data, …\) to help peer robots which are out of range.

I believe there are a couple options for how this could work:

**1\) Competitor-defined nodes**

Each communications node could be defined similarly to a robot. No locomotion/actuators/sensors would be necessary. The node would have 2 states: `carried` and `dropped`. It would be somehow tied to a parent robot \(e.g. maybe by name – COMM1X1 could be a comm node carried by a robot named X1\). An ROS service could be used to change the state from `carried` to `dropped`. Upon entering the dropped state, the node position would no longer be tied to the parent robot, and normal physics rules would apply.

This option would allow the competitors to write custom controller code for the node, and it would be subject to the same limitations as other robots \(operating on its own isolated VM, limited by communication distances, etc…\). The node would, however, only be capable of communications and data processing related functionality due to its lack of sensors and actuation.

**2\) Predefined nodes**

In this case, each communications node could be defined similarly to a sensor/actuator. It would run predefined code capable of some functions such as repeating a message to another destination and/or queryable data storage. A robot could carry several of these nodes, as defined by its sensor configuration. Again, an ROS service could be used to change the state from `carried` to `dropped`, at which point it would no longer be tied to its parent robot, and normal physics rules would apply.

**Comment by nkoenig** [comment]
[Communication breadcrumbs](https://github.com/osrf/subt/wiki/Breadcrumbs-and-communication-visualization-tutorial) have been added to simulation.
