### ISSUE TITLE
ign log playback issue

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#311]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/311)) by Steven Gray (Bitbucket: [stgray](https://bitbucket.org/%7B7470e809-c304-4b17-b986-685f31fa15c3%7D/)).**

----------------------------------------
Followed the instructions on [https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/wiki/tutorials/cloudsim\_log\_playback](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/wiki/tutorials/cloudsim_log_playback).  

Extracting and starting playback are fine, but it’s looking for the meshes in the docker location:

```
[GUI] [Err] [Ogre2MeshFactory.cc:430] Cannot load null mesh [file:///home/developer/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/Rescue Randy Sitting/1//meshes/rescue_randy.dae]
[GUI] [Err] [Ogre2MeshFactory.cc:72] Failed to get Ogre item for [file:///home/developer/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/Rescue Randy Sitting/1//meshes/rescue_randy.dae]
[GUI] [Err] [SceneManager.cc:275] Failed to load geometry for visual: visual
```

Is there a command-line option to substitute something else for this?  I ended up copying my `.ignition` folder over to the home directory it was looking for and `chown`-ing it.

Also - the fast forward/seek doesn’t seem to work?  Hovering over the fast forward button, I can enter a number of steps \(I tried 5000\) and there’s no change.

‌

**Comment by nkoenig** [comment]
Closing due to age of the issue.
