### ISSUE TITLE
X2 robot gets stuck on lip between urban service room and urban_straight_door_right

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#320]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/320)) by Steven Gray (Bitbucket: [stgray](https://bitbucket.org/%7B7470e809-c304-4b17-b986-685f31fa15c3%7D/)).**

----------------------------------------
Have been noticing that the robot gets hung up on what looks like a few centimeter lip between the floor levels here.  There’s a gap that the railing can be seen through.

![](https://osrf-migration.github.io/subt-gh-pages/data/bitbucket.org/repo/8ze6Mjd/images/3613938169-Screenshot_from_2020-01-03_22-47-02.png)
‌

**Comment by nkoenig** [comment]
Velocity and acceleration limits have been applied to the robot models.

I'll check the urban models for gaps.

**Comment by nkoenig** [comment]
I have confirmed that there is no gap and the X2 can drive over the lip. Please reopen if the problem persists.
