### ISSUE TITLE
Obtain Ground Truth while using SLAM

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#325]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/325)) by Joe Palk (Bitbucket: [jepalk](https://bitbucket.org/%7B5cc8ea43-8141-495c-84a6-d43c27045e87%7D/)).**

----------------------------------------
Hello!

Is there a good way to use the enableGroundTruth:=true option while simultaneously running a SLAM solution, like Cartographer?  This currently seems to create a conflict, since the enableGroundTruth option creates a parent-child relationship between the world frame and the robot frame in the tf tree, but a solution like Cartographer also creates parent-child relationship between the generated map and the robot.  This causes some funny issues when I try to run them together, since I believe the tf package only allows each frame to have one parent frame.  In particular, if I use a tool like view\_frames to monitor the tf tree, the tree seems to flip-flop between the urban\_circuit\_practice\_xx and cartographer map frames as the parent frame to X1.

I would love to be able to record both the actual and the estimated positions at the same time to compare them.

**Comment by yuthikasagarage** [comment]
Is it possible to just publish ground truth without having to meddle with the frames in ign? i'm using some lidar odometry package with ekf localization. i need to compare the groundtruth with it. Since, enableGroundTruth:=true option makes a tf between world and the robot name , it's conflicting.

**Comment by nkoenig** [comment]
Ground truth pose information can be found on the `/world/<world_name>/dynamic_pose/info` topic.

**Comment by pauljurczak** [comment]
I just reinstalled SubT from master and I don't see this topic
```
paul@desktop:~$ ign launch -v 0 cave_circuit.ign worldName:=cave_qual robotName1:=X1 robotConfig1:=X3_SENSOR_CONFIG_5 enableGroundTruth:=true
...
paul@desktop:~$ rostopic list
/X1/air_pressure
/X1/battery_state
/X1/bottom_scan
/X1/cmd_vel
/X1/front/camera_info
/X1/front/depth
/X1/front/depth/compressed
/X1/front/depth/compressed/parameter_descriptions
/X1/front/depth/compressed/parameter_updates
/X1/front/depth/compressedDepth
/X1/front/depth/compressedDepth/parameter_descriptions
/X1/front/depth/compressedDepth/parameter_updates
/X1/front/depth/theora
/X1/front/depth/theora/parameter_descriptions
/X1/front/depth/theora/parameter_updates
/X1/front/image_raw
/X1/front/image_raw/compressed
/X1/front/image_raw/compressed/parameter_descriptions
/X1/front/image_raw/compressed/parameter_updates
/X1/front/image_raw/compressedDepth
/X1/front/image_raw/compressedDepth/parameter_descriptions
/X1/front/image_raw/compressedDepth/parameter_updates
/X1/front/image_raw/theora
/X1/front/image_raw/theora/parameter_descriptions
/X1/front/image_raw/theora/parameter_updates
/X1/front/optical/camera_info
/X1/front/optical/depth
/X1/front/optical/image_raw
/X1/gas_detected
/X1/imu/data
/X1/magnetic_field
/X1/output/camera_info
/X1/pose
/X1/pose_static
/X1/rgbd_camera/depth/points
/X1/top_scan
/X1/velocity_controller/enable
/clock
/rosout
/rosout_agg
/statistics
/subt/run_clock
/subt/score
/tf
/tf_static
```

**Comment by peci1** [comment]
I've written a ROS-Ign node that publishes a `world->X1_ground_truth` transform which does not conflict with other mapping frameworks.  It also detects the position of `artifact_origin` inside the `world` frame and publishes it as static transform `world->subt`. To use this node, do **not** launch the simulator with `enableGroundTruth:=true`.

https://gist.github.com/peci1/3afa492011267a4313a071a64c58e35a

**Comment by yuthikasagarage** [comment]
it is an ign topic, not a rostopic. what you can do is subscribe to ign topic and publish your own odometry to a rostopic.
