### ISSUE TITLE
Feature Request - Robot Batteries Discharge Slower When Not Moving

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#333]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/333)) by GoRobotGo (Bitbucket: [GoRobotGo](https://bitbucket.org/%7B2fd8dac8-286d-461a-b7dd-dba99deea025%7D/)).**

----------------------------------------
This is a feature request for the robot batteries to not discharge or to discharge slower when they are stationary.  Currently the battery starts discharging on first motion and continues discharging at a fixed rate even if the robot is no longer in motion.

**Comment by acschang** [comment]
This has been completed as of [Cave Feature Release 2](https://github.com/osrf/subt/wiki/release_notes#2020-06-11) and the behavior is documented on the [Battery Plugin wiki page](https://github.com/osrf/subt/wiki/Battery-Model-Tutorial).
