### ISSUE TITLE
Handling /subt/finish for multiple robots

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#336]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/336)) by Martin Dlouhy (Bitbucket: [robotikacz](https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/)).**

----------------------------------------
How does it work with topic `/subt/finish` with multiple robots? Does it hold for a single robot all for the whole group?

I am referring to:

[https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/wiki/api](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/wiki/api)

_It's good practice to call the finish service when you are done with a competition run. The finish service will automatically be called when any of the termination criteria are met \(refer to the SubT Challenge rules document\)._ 

I just realized that one of the reason why the simulation is cut in the middle is that one of five simulated robots returned home and called `/subt/finish` … so does it behave that any robot can terminate it? It is not “per robot” correct?

**Comment by angelacmaio** [comment]
`/subt/finish` will remain a global call so any robot can terminate the run. The "Stop" button on the SubT Virtual Portal can also be used to end the run early.
