### ISSUE TITLE
Cloudsim version of tunnel qualifier

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#337]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/337)) by Steven Gray (Bitbucket: [stgray](https://bitbucket.org/%7B7470e809-c304-4b17-b986-685f31fa15c3%7D/)).**

----------------------------------------
DARPA \(via email\) has indicated that for the cave circuit, they are considering allowing teams to qualify against any of the previous qualifiers.  Would it be possible to get a cloudsim version of the tunnel qualifier to test against?

**Comment by nkoenig** [comment]
I believe this issue is complete; closing.
