### ISSUE TITLE
Why not use more static transforms?

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#338]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/338)) by Paul Jurczak (Bitbucket: [pauljurczak](https://bitbucket.org/%7Bd17ee528-259a-4ff4-b5b0-007442ea3edb%7D/)).**

----------------------------------------
At present only `X1` → `X1/base` is published as a static transform. There are number of transforms from `X1/base` to sensors, which are mechanically static, but published as non-static transforms eating up the bandwidth. Is there a reason for it? Can it be changed?

**Comment by nkoenig** [comment]
Resolved in #402
