### ISSUE TITLE
Sporadic move_base failure in CloudSim: "Unable to get starting pose of robot, unable to create global plan"

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#348]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/348)) by Malcolm Stagg (Bitbucket: [malcolmst7](https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/)).**

----------------------------------------
This is probably just something I’m doing wrong, so my apologies for bothering everyone else with this, but I wanted to ask if anyone else has had move\_base sporadically fail with the error: 

```
Unable to get starting pose of robot, unable to create global plan
```

I’m seeing this sporadically but very frequently in a lot of CloudSim logs. Never saw it happen locally. I was assuming it might be related to one of the CloudSim issues before the urban competition, but now I’m not so sure. When it happens, it fills up the logs with the same message over and over, and the robot never recovers. I’m guessing it might be \(directly or indirectly\) caused by some sort of a SLAM failure, but it just seems a little strange I’ve never had it happen in local testing.

Anyway, I will keep on digging \(pun intended\) into this a lot more here, but just wanted to quickly ask if anyone else has seen something like this?

Thanks, much appreciated!

**Comment by nkoenig** [comment]
This issue was likely tied to issue #261. I'll close this next week unless someone speaks up.

**Comment by nkoenig** [comment]
Closing.
