### ISSUE TITLE
Replace CommsClient by ROS topic(s)?

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#35]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/35)) by Martin Dlouhy (Bitbucket: [robotikacz](https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/)).**

----------------------------------------
Is there any plan to replace CommsClient with ROS interface, i.e. that we could "publish" detected artifacts instead of creation of C++proxy?? We are using ROS from Python "externally", which is probably not very common use case :(. Thank you.

**Comment by peci1** [comment]
Well, there actually already is a ROS-only API provided by [subt_ros_relay](https://github.com/osrf/subt/blob/d5f8fe760cd6f0e68a6a9a615f143b74d82d07dc/subt_ros/src/SubtRosRelay.cc#L343). I think it'd satisfy everything you need to successfully communicate via the comms plugin.

When I list the services created by subt_ros_relay, I see:

```
/address/register
/address/unregister
/broker
/end_point/register
```

The missing piece is IMO what I found in #638: to listen for incoming data on `address`, you create a `subt_msgs/DatagramRos` service server name `/address`. Of course, this still suffers from the inability to create multiple listening nodes, but you can create a "demux" relaying the service calls to a topic as I'm suggesting in #638.

`/broker` is a weird name, but it is the thing you want to call when sending messages to the comms interface.
