### ISSUE TITLE
Feature Request: Service indicating scoring time period

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#351]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/351)) by Reid Sawtell (Bitbucket: [rsawtell](https://bitbucket.org/%7B845ed98c-79aa-4771-ab0d-6d8424f27344%7D/)).**

----------------------------------------
It would be convenient to have a service indicating the start/end times of the simulation scoring period. This would allow better coordination of robots with respect to the simulation period without worrying about potentially changing rules such as automatic scoring start interval or changes to the simulation duration, as well as helping overcome other issues such as robots crashing or unable to communicate due bridge failures that can sometimes make inference of the start time difficult.

**Comment by angelacmaio** [comment]
See the new [competition clock](https://github.com/osrf/subt/wiki/api#competition-clock) topic.

**Comment by zwn** [comment]
@angelacmaio How does this work in relation of starting/loading the individual robots? Does this new topic help in any way in coordinating the start of the robots? There was no way how to detect that all virtual machines for all the robots has been loaded - we see different delays maybe related to the size of the respective docker image - leading to a situation when one robot is already loaded in the simulation while others are not.

Which leads me to the question: when exactly does this new topic change to `run`? What is the trigger? Is this something we can wait on with all the robots to ensure coordinated start?

**Comment by angelacmaio** [comment]
The loading of robots is a different issue in discussion [here](https://github.com/osrf/subt/issues/412). 

The conditions for triggering the start and end of the scoring time period are described in the [API Wiki here](https://github.com/osrf/subt/wiki/api#starting-and-finishing-a-trial).
