### ISSUE TITLE
RGBD Camera error upon launch

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#353]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/353)) by Ashton Larkin (Bitbucket: [Ashton Larkin](https://bitbucket.org/%7B0d8d5c66-3903-4ba7-bffc-1dbdc96eece7%7D/)).**

----------------------------------------
I am using the urban\_circuit branch. Whenever I try to use a robot with an RGBD camera on it, I get the following error message:

```
[ERROR] [1583876839.521854511, 20.896000000]: Compressed Image Transport - JPEG compression requires 8/16-bit color format (input format is: 32FC1)
[ERROR] [1583876839.522223726, 20.896000000]: cv_bridge exception: '[32FC1] is not a color format. but [bgr8] is. The conversion does not make sense'
```

This started to happen about an hour ago. Interestingly enough, I have been using the same robot for about two weeks now, and this error never started to appear until today. Here is the command I am using:

```
ign launch -v 4 urban_circuit.ign worldName:=urban_circuit_practice_01 robotName1:=X1 robotConfig1:=COSTAR_HUSKY_SENSOR_CONFIG_1
```

I have also tried to launch other robots with RGBD cameras, and I still get the same error:

```
ign launch -v 4 urban_circuit.ign worldName:=urban_circuit_practice_01 robotName1:=X1 robotConfig1:=COSTAR_HUSKY_SENSOR_CONFIG_1
ign launch -v 4 urban_circuit.ign worldName:=urban_circuit_practice_01 robotName1:=X1 robotConfig1:=EXPLORER_X1_SENSOR_CONFIG_1
```

‌

**Comment by nkoenig** [comment]
Closing since the release on 2020-04-06 fixed the issue.
