### ISSUE TITLE
Uncomplete log file for download

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#356]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/356)) by Zbyněk Winkler (Bitbucket: [Zbyněk Winkler (robotika)](https://bitbucket.org/%7Bd253a02a-aa23-4c28-9bf2-75863acb0ee0%7D/)).**

----------------------------------------
I am trying to unpack the file `ver59uw2a-b2e9d531-5859-42d1-816f-9794cd568b38.tar` however that file seems to be incomplete. Running `tar -xf` on it gives me the following error:

```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

I guess there is no way to recover this particular file \(there is no jurnal file and no summary either inside and the state.tlog seems to be corrupted as well\). 

However, can we find out how such a thing happens and fix the cause?

**Comment by nkoenig** [comment]
Unfortunately there is no way to recover this log file. Cloudsim has been significantly improved since March. I'll close this issue in order to triage the issue tracker.
