### ISSUE TITLE
Controlling Pan Tilt Gimbal using JointControlPlugin and JointStatePublisher

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#357]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/357)) by Brett Fotheringham (Bitbucket: [Bfotheri](https://bitbucket.org/%7Bc663faa7-940e-4976-9a88-063429949e2c%7D/)).**

The original report had attachments: [model.sdf](https://osrf-migration.github.io/subt-gh-pages/data/repositories/osrf/subt/issues/357/attachments/model.sdf)

----------------------------------------
Hey guys,

We are trying to submit a new robot which has an rgbd camera on the end on a pan tilt gimbal but I have run into a problem. Note: I have been working exclusively with the model.sdf file up till now. So the joints and links appear to be setup properly in the SDF file but now I am unsure of how to use the JointControlPlugin and JointStatePublisher \(which are both supported in Ignition-blueprint\). Does anyone have any advice for how to use these plugins in ignition? I’ve been looking over ignition and gazebo documentation but am still pretty lost. Thanks for the help!

Brett Fotheringham

‌

**Comment by angelacmaio** [comment]
Supporting [PR](https://github.com/ignitionrobotics/ros_ign/pull/64) was merged and released. The pan/tilt gimbals on the robots are functional.
