### ISSUE TITLE
CloudSim - feature: manual termination

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#361]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/361)) by Martin Dlouhy (Bitbucket: [robotikacz](https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/)).**

----------------------------------------
It would be nice to be able to manually terminate simulations running on CloudSim when we know that they will fail \(or worse never end\).

Currently ver59cave1 \(f5f60f31-c00d-4d57-897e-959a2e87517f\), ver59cave2 \(df530ef1-d495-45c2-84c3-55961c9f5d94\), ver59cave3 \(d3796662-25da-4306-9b21-36502e50dfc9\)

**Comment by m3d** [comment]
I see I already created this issue "some time ago" :) ... now it is great that you can watch, what is going on, so I see that the robot returned to the start, or is up-side-down ... and it does not really have sense to simulate it any further (note, that our test runs are typically only 5 minutes of simtime). So it would be nice to "kill it" and start new one (I know that I can start another simulation, but it is a bit waste of resources).
Thanks for great progress since Tunnel last year!

**Comment by nkoenig** [comment]
Thanks for the reminder. I've assigned this issue to @cameron-ridgewell, who is in charge of the SubT Portal.

**Comment by m3d** [comment]
This feature is now getting more and more valuable as the number of simulations is limited to 3 running in parallel ...
(+ not speaking about simulation of 10 robots)

**Comment by m3d** [comment]
p.s. at the moment we have 2 pending simulations (one for 8 hours already), and it could happen that by the time they will be ready to run we will no longer need them ... but we would like to use "our" time slot ...

**Comment by wolfgangschwab** [comment]
We also vote for this feature. Often you can see after a view simulation-minutes whether it makes sense to run the complete time or not.  So it would be really helpful to be able to stop/kill running simulations on cloudsim. And also it would save resources :-) and also help other teams. 

I started a simulation 15 minutes ago and it is still "Pending" although we have currently no other simulation running. (It's all your fault Martin, you are blocking everything ;-) )

**Comment by nkoenig** [comment]
The Subt Portal now has a stop button which will let you cancel a simulation run.

**Comment by wolfgangschwab** [comment]
I noticed that new button, but had not any more the need to use it. But this will be very helpful in the future. 

Thanks!!!!!!!!!!!!!

**Comment by zwn** [comment]
The stop button does not seem to be doing anything on 647febbd-a255-4b5d-bc83-e7febde9316d
