### ISSUE TITLE
Record functionality within Ignition does not automatically append file extension

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#362]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/362)) by Arthur Schang (Bitbucket: [Arthur Schang](https://bitbucket.org/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D/)).**

----------------------------------------
The record function asks the user to choose between two codecs and name the output file but does not append the user's selected codec file type to the output file name.

**Comment by JShep1** [comment]
A PR has been created [here](https://github.com/ignitionrobotics/ign-gazebo/pull/303) which will automatically append the selected video format extension to the filename that the user enters.

**Comment by nkoenig** [comment]
PR has been merged, and a release is coming out today.
