### ISSUE TITLE
Cave artifacts

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#368]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/368)) by Chris Fotache (Bitbucket: [chrisfotache](https://bitbucket.org/%7Bcd3b9ed2-9a40-452b-ab2c-331d13096957%7D/)).**

----------------------------------------
Is there an official list of cave circuit artifacts?

**Comment by angelacmaio** [comment]
Cave artifacts have been announced with details in the [Artifacts Specification Guide](https://subtchallenge.com/resources/SubT_Cave_Artifacts_Specification.pdf) and models on the [SubT Tech Repo](https://subtchallenge.world/openrobotics/fuel/collections/SubT%20Tech%20Repo).
