### ISSUE TITLE
DepthCloud from RGBD shows in incorrect orientation in RVIZ

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#369]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/369)) by Hector Escobar (Bitbucket: [hector_escobar](https://bitbucket.org/%7B1c140a49-f2c5-4727-abd9-eb427bfe4253%7D/)).**

----------------------------------------
I just tried the x4 config 2 and when plotting the DepthCloud of the RGBD it shows facing up. The sensor information is correct but the display has a rotation error. 

![](https://osrf-migration.github.io/subt-gh-pages/data/bitbucket.org/repo/8ze6Mjd/images/1160430657-depthUpsidedown.png)
‌

**Comment by gglaspell** [comment]
Is there a temporary work around for this? Can you simply rotate the pose in the SDF file? Or, can you assign a static transform to perform the rotation?

**Comment by angelacmaio** [comment]
The optical frame publisher is now available for all cameras. This is documented in the [API wiki](https://github.com/osrf/subt/wiki/api#sensors):
> For 2D camera, Stereo camera, and RGBD camera sensors, the image and depth data are also available in optical frame (z forward, x right, y down) via topics with the /optical/ string in the topic name. More information on coordinate frame conventions can be found in REP 103.

The `/optical/` topics should display in the correct orientation in RViz.

**Comment by nkoenig** [comment]
Closing since the optical frame solves this issue.
