### ISSUE TITLE
Modification of existing vehicle ROBOTIKA_X2_SENSOR_CONFIG_1

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#370]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/370)) by Martin Dlouhy (Bitbucket: [robotikacz](https://bitbucket.org/%7B27de76db-249c-44be-9eb8-91a3b17bf0d7%7D/)).**

----------------------------------------
Hello,

we would like to update our model “ROBOTIKA\_X2\_SENSOR\_CONFIG\_1” from Virtual Urban Circuit. Is there some recommendation regarding naming of forks , PR, etc? \[it is simple alignment with updated default X2\]

thanks

‌    Martin/Robotika Team

**Comment by angelacmaio** [comment]
See [PR #380](https://github.com/osrf/subt/pull/380)
