### ISSUE TITLE
Visible seams between cave segments

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#373]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/373)) by Paul Jurczak (Bitbucket: [pauljurczak](https://bitbucket.org/%7Bd17ee528-259a-4ff4-b5b0-007442ea3edb%7D/)).**

----------------------------------------
I can see seams between segments in multiple locations in `simple_cave_01` world:

![](https://osrf-migration.github.io/subt-gh-pages/data/bitbucket.org/repo/8ze6Mjd/images/2999195954-cave_01_seems.png)
‌

**Comment by nkoenig** [comment]
@mjcarroll , can you check to see if this problem is still present?

**Comment by mjcarroll** [comment]
`[(10) tile_10(Cave 3 Way 01 Type B)] -- [(11) tile_11(Cave Elevation Type B)] [387.5 75 0] `
![image](https://user-images.githubusercontent.com/279701/91752459-0597ba80-eb8c-11ea-8675-0fdf97e5125e.png)

**Comment by mjcarroll** [comment]
`[(26) tile_26(Cave Straight 03 Type B)] -- [(27) tile_27(Cave Corner 02 Type B)]
[337.5 25 0]`
![image](https://user-images.githubusercontent.com/279701/91753032-df264f00-eb8c-11ea-8e28-4261cfe065e7.png)

**Comment by mjcarroll** [comment]
These were the two seams that I could find using the connection validator tool. They seem to be on the floor in the z-direction only, rather than on the walls as originally reported.

**Comment by nkoenig** [comment]
I'm closing this issue the step between tiles is less than 0.01m and should be easily traversible by all robots.
