### ISSUE TITLE
SHA hashes of docker images

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#377]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/377)) by Malcolm Stagg (Bitbucket: [malcolmst7](https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/)).**

----------------------------------------
The new logging changes pushed today seem to be causing some problems for my robots, still investigating what is happening there.

I no longer have a copy of the previous docker image versions though for `osrf/subt-virtual-testbed:cloudsim_bridge_latest` and `osrf/subt-virtual-testbed:cloudsim_sim_latest`. I think these images are still available on dockerhub if you have the SHA hash. Unfortunately I don’t seem to have that hash for the previous version. 

I was wondering if it would be possible for SHA hashes to be published along with the released docker images in the future?

Also, if anyone has the SHA hashes available for the 03/29 images I would appreciate it :\). Thanks!

**Comment by angelacmaio** [comment]
SHA hashes are now included in the [Release Notes](https://github.com/osrf/subt/wiki/release_notes) for each new docker image release.
