### ISSUE TITLE
Proceeding with Model Submission on github

### ISSUE THREAD

**Issue by bfotheri** [osrf/subt#393]
Hey guys,

We have a few sensor model updates we need to make to our new submitted robot models but are not sure how to proceed. Would you like us to fork this repo, update the branches that correspond to our submissions, and then submit another PR for the updates to those branches? Thanks guys.

Brett Fotheringham

**Comment by acschang** [comment]
That process will work.

**Comment by angelacmaio** [comment]
Agreed, forking and submitting another PR is the best way to make changes. Since the model submission deadline has passed, significant changes may or may not be incorporated.
