### ISSUE TITLE
Ignition, ROS and Ubuntu version upgrade 

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#429]
SubT software platform is based on Ignition Blueprint, ROS Melodic and Ubuntu 18.04. As of tomorrow, the new versions of all these platforms will be available: Ignition Citadel, ROS Noetic and Ubuntu 20.04. Given extension of deadlines for Cave Circuit, are there any plans to upgrade SubT software platform to the newest components?

**Comment by nkoenig** [comment]
We are not planning to change software version for Cave Circuit. The rationale is that changing software versions can disrupt teams and requires thorough vetting.

It's possible that we will change versions for the final competition.
