### ISSUE TITLE
CUDA 11 problem

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#549]
Docker Install (https://github.com/osrf/subt/wiki/Docker%20Install) will cause CUDA 11 docker image to get installed, which doesn't have official driver support on Ubuntu 18.04 yet. Verify Nvidia docker installation should change from:
```
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
```
to
```
docker run --runtime=nvidia --rm nvidia/cuda:10.2-base nvidia-smi
```
for those who have the most current official Nvidia driver (440.100) on Ubuntu 18.04.

**Comment by nkoenig** [comment]
Thanks the instructions have been updated.
