### ISSUE TITLE
Error in description of EXPLORER_DS1

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#558]
Both https://www.subtchallenge.world/openrobotics/fuel/models/EXPLORER_DS1_SENSOR_CONFIG_1 and https://github.com/osrf/subt/wiki/Robots have `3 x QVGA RGBD cameras` in EXPLORER_DS1 description. This robot has `3 x VGA RGBD cameras` instead, see `EXPLORER_DS1_SENSOR_CONFIG_1/model.sdf`:
```
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
```

**Comment by nkoenig** [comment]
Thanks for the catch. The wiki and tech repo have been fixed.
