### ISSUE TITLE
Rules state 5 robots of a given type are allowed, submission only allows 4

### ISSUE THREAD

**Issue by rsawtell** [osrf/subt#564]
The simulation submission dialogue will give the following error: "Error #5522: Too many robots of a single model." when submitting a run with 5 robots of the same type, though it works with submitting only 4.

Based on https://www.subtchallenge.com/resources/SubT_Challenge_Cave_Rules.pdf section 10.3.1 I would expect 5 robots of a given type to work, have the rules changed or is the submission dialogue bugged?

**Comment by nkoenig** [comment]
Can you let me know what robot types you were submitting?

**Comment by rsawtell** [comment]
Sent an e-mail to subt-help with the information.

**Comment by acschang** [comment]
We have confirmed the issue.

**Comment by nkoenig** [comment]
@rsawtell , can you please try once more? A patch has been rolled out on cloudsim.
