### ISSUE TITLE
Leaderboard multipage rank

### ISSUE THREAD

**Issue by m3d** [osrf/subt#590]
There are more than 10 teams qualified now, but the "Rank" is probably wrong on the 2nd page ... no big deal, just FYI.

https://subtchallenge.world/leaderboard

![multipage-bug](https://user-images.githubusercontent.com/5664353/92022761-0a12cd80-ed5c-11ea-83d3-00d940465f1f.png)

**Comment by nkoenig** [comment]
Hello Martin,

Thanks for pointing this out, we are working on a fix.

nate

**Comment by angelacmaio** [comment]
Resolved
