### ISSUE TITLE
Color of Breadcrumbs in Couldsim 

### ISSUE THREAD

**Issue by wolfgangschwab** [osrf/subt#591]
I just noticed that the breadcrumbs in the Web visualization of the SubT Portal are shown in black. In my local Simulation they appear in orange. What is the expected color in Clouldsim?

**Comment by nkoenig** [comment]
Fixed in version 4 of https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Breadcrumb%20Node

**Comment by angelacmaio** [comment]
Resolved
