### ISSUE TITLE
BridgeLogger should allow defining custom ignore suffixes.

### ISSUE THREAD

**Issue by peci1** [osrf/subt#595]
In our system, we use a custom image transport which creates topics like `/camera/front/image_raw/h264`. With BridgeLogger, these topics are automatically subscribed, which causes unnecessary load to the system as we don't need this transport on all cameras.

Could you please provide a way to add more ignore suffixes to the BridgeLogger?

**Comment by peci1** [comment]
Solution proposed in #757.

**Comment by nkoenig** [comment]
Resolved in #757.
