### ISSUE TITLE
Wiki: Add LC_ALL=C to local playback

### ISSUE THREAD

**Issue by peci1** [osrf/subt#610]
The playback command in https://github.com/osrf/subt/wiki/Cloudsim-Log-Playback#local-playback should have `LC_ALL=C` prepended to avoid #438. It's much easier to put it in the tutorial than fixing the places in code that are responsible.

**Comment by nkoenig** [comment]
Good idea. Added: https://github.com/osrf/subt/wiki/Cloudsim-Log-Playback#local-playback

**Comment by peci1** [comment]
Thanks.
