### ISSUE TITLE
power_load parameter

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#617]
Is increasing `power_load` parameter used exclusively to reduce battery life from 20 minutes for UAV or it affects performance of the robot, e.g. higher maximum speed with higher `power_load`?

**Comment by azeey** [comment]
If the question is whether the simulator looks at the `power_load` parameter to determine the maximum speed, the answer is no. The maximum speed is set by the parameters of the `MulticopterVelocityControl` and `MulticopterMotorModel` plugins.

**Comment by pauljurczak** [comment]
Yes, that was my question. In the real world you could sacrifice battery life for higher performance. I wanted to verify that this is not being the case in this simulation.

**Comment by azeey** [comment]
That's true. Unfortunately, only constant power loads are supported in the simulator right now.
