### ISSUE TITLE
Depth image noise

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#630]
Until a while ago, there was no noise added to depth images other than some small 3D geometry artifacts. Recently, I noticed a significant noise added to depth data from VGA RGBD camera on X3 and DS1 robots. Is this an intentional improvement in simulation realism across all RGBD and ToF cameras?

**Comment by angelacmaio** [comment]
Support for RGBD noise was added with: https://github.com/ignitionrobotics/ign-rendering/pull/122
As a result, the noise parameters that have always resided in this repo became supported for improved realism.

**Comment by zwn** [comment]
It would have been nice if such a major change was mentioned at https://github.com/osrf/subt/wiki/release_notes
