### ISSUE TITLE
Velocity and acceleration limits for SubT robots

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#637]
I found these parameters only for a few robots in their .sdf files, but most of them don't specify them there. I tried `~/.ignition/fuel/fuel.ignitionrobotics.org/OpenRobotics/models` and downloads from https://www.subtchallenge.world/openrobotics/fuel/models. Where else should I search?

There are velocity and acceleration limits in files like `~/subt_ws/install/share/marble_hd2_sensor_config_2/launch/spawner.rb`. How are they related to the "true" limits?

**Comment by nkoenig** [comment]
The velocity limits for a model are found in plugins. The submitted models will have limits in their respective `spawner.rb` scripts. The models created by DARPA and OSRF use plugins specificed in [launch scripts](https://github.com/osrf/subt/blob/master/subt_ign/launch/cloudsim_sim.ign#L748).
