### ISSUE TITLE
Unable to install ROS packages today

### ISSUE THREAD

**Issue by malcolmst** [osrf/subt#657]
This may just be a temporary issue, but FYI I am unable to build a new docker image today due to `packages.ros.org` not working. It looks like the https://www.ros.org/ domain may have expired today.

**Comment by mjcarroll** [comment]
There was a slight hiccup in the domain, should be resolved now.

Let us know if there are continued issues (after DNS has a chance to propagate).

**Comment by mjcarroll** [comment]
Tracking issue for reference: https://github.com/osrf/www.ros.org/issues/92

**Comment by malcolmst** [comment]
Working fine now, thanks!
