### ISSUE TITLE
RSSI reported by robot seems to be infinity

### ISSUE THREAD

**Issue by arjo129** [osrf/subt#664]
```
[Dbg] [VisibilityRfModel.cc:80] Range: 12.3693, Exp: 1.5, TX: 20, RX: -36.3852
[Dbg] [VisibilityRfModel.cc:80] Range: 2.00437, Exp: 1.5, TX: 20, RX: -24.5297
[Dbg] [VisibilityRfModel.cc:80] Range: 0, Exp: 1.5, TX: 20, RX: inf
[Dbg] [VisibilityRfModel.cc:80] Range: 12.3693, Exp: 1.5, TX: 20, RX: -36.3852
[Dbg] [VisibilityRfModel.cc:80] Range: 2.00437, Exp: 1.5, TX: 20, RX: -24.5297
[Dbg] [VisibilityRfModel.cc:80] Range: 0, Exp: 1.5, TX: 20, RX: inf
```
So I have a teambase and one husky. If I call `get_neighbours` on teambase it gives me the rssi to the robot. On the other hand the robot reports an RSSI range of Infinity. Not sure what to make of this.

**Comment by arjo129** [comment]
Duplicate of #643

**Comment by peci1** [comment]
And do you actually read the robot the `inf` RSSI is associated with? Because when you publish to broadcast, you also publish to yourself (with `inf` RSSI).
