### ISSUE TITLE
Cloudsim re-adding runs and stop button not working

### ISSUE THREAD

**Issue by realdealneil** [osrf/subt#672]
We have noticed a few times when cloudsim has run some of our runs more than once even though we only uploaded once. (Team Collembola).  One example is tbs1014qualr1 (ID: 356639c0-6344-4e57-8dbb-c87981b0054a-r-1).  Note that it ran yesterday and then reran itself today (has the exact same ID both times).  This wouldn't be a problem if we could stop the runs (cancel them), but the cancel button doesn't seem to do anything.  We get a confirmation screen, we hit ok, but the run keeps on going.

**Comment by malcolmst** [comment]
The cancel button is working for me now, though I was also having some trouble with it not working earlier. I think the r1 runs usually happen automatically when the first run fails (sometimes anyway).

**Comment by nkoenig** [comment]
I'll close this issue because the cancel button is working.
