### ISSUE TITLE
Robots falling through the floor in different worlds

### ISSUE THREAD

**Issue by wolfgangschwab** [osrf/subt#675]
Sorry about the late reporting of this issue. We just noticed this behaviour only a two days ago and were too busy with the ending submission window to report this earlier. 

We noticed in about 2/3 of our runs that robots were falling through the floor. This happened in different worlds. 
We really would appreciate a fix of this issue before the cave circuit runs start. 

Here are some short videos of such fallings:
Cave Practice 1:
![CP1-falling-X2n2-0860](https://user-images.githubusercontent.com/60989112/96323008-a1399900-101b-11eb-8b87-60fa07c12938.gif)

Cave Practice 3:
![CP3-falling-X2n1-0320](https://user-images.githubusercontent.com/60989112/96323022-b1ea0f00-101b-11eb-8df2-cb65b9a96d10.gif)

Cave Qualification:
![CQ-falling-X1n1-0010](https://user-images.githubusercontent.com/60989112/96323034-c29a8500-101b-11eb-9720-6371d7f6b6cb.gif)

Cave Simple 1:
![CS1-falling-X2n1-1120](https://user-images.githubusercontent.com/60989112/96323115-1c02b400-101c-11eb-96e3-bc8fc9cc8b8d.gif)

Cave Simple 3:
![CS3-falling-X1n1-0020](https://user-images.githubusercontent.com/60989112/96323123-23c25880-101c-11eb-8fb7-b5b7e1847b9f.gif)

These were all cloudsim runs. If you need more informations, I can provide them.

**Comment by nkoenig** [comment]
This is happening because your solution is sending `nan` values to `cmd_vel` and physics is not able to handle this case. There is a patch to physics here: https://github.com/ignitionrobotics/ign-physics/pull/137. I also recommend modifying your code to eliminate the `nan` values.

We have seen the `nan` values in the ROS logs:
```
84.272000000 INFO /X2n2_robot_controller [/home/developer/workspaces/subt_seed_ws/src/subt_seed/src/robot_Controller.cpp:4832(setVelocties)] [topics: /rosout, /X2n2/cmd_vel, /X2n2/wand_visualization_marker, /X2n2/checkNodeList_req, /X2n2/checkNodeList_and_insert_req, /X2n2/checkEdgeList_req, /X2n2/checkEdgeList_and_insert_req, /X2n2/shortestPath_req, /X2n2/nearestEdge1End_req, /X2n2/artefaktmeldungen, /X2n2/breadcrumb/deploy, /statistics]   cmd_vel tatsaechliche Vorgabe: vx=1.349041, vy=0.000000, vz=0.000000, angz=nan
```

**Comment by wolfgangschwab** [comment]
Hi Nate, 

thank you very much for the feedback. We did not expect this reason. We definitely will change your controller to avoid sending a nan. But thanks for fixing it in ign-physics. 

Wolfgang
