### ISSUE TITLE
Position in run.yml reported not wrt artifact origin

### ISSUE THREAD

**Issue by zwn** [osrf/subt#678]
We got this from `run.yml` in one of our runs in Cave Practice 1:

<pre>
closest_artifact_report:
 name: phone_2
 type: TYPE_PHONE
 true_pos: 235.343 -269.237 24.5257
 reported_pos: 235.99 -268.98 24.54
 distance: 0.6964706787058702 
</pre>

The artifact origin in this world is set at [[10.0, 0.0, 0.0]](https://github.com/osrf/subt/blob/840975255690efaa16ca2d851ff8e606fc126648/subt_ign/worlds/cave_circuit_practice_01.sdf#L34-L38).
The position of the artifact is [[235.363, -269.258, 24.450999999999993]
](https://github.com/osrf/subt/blob/840975255690efaa16ca2d851ff8e606fc126648/subt_ign/worlds/cave_circuit_practice_01.sdf#L434-L438).

I am not sure where the said "true_pos" comes from: `[235.343, -269.237, 24.5257]`

It seems to be missing the offset for artifact origin so 235.343 should become 225.343. But the values of Y and Z differ: -269.237 and -269.258 differ by 0.02m; 24.450999999999993 and 24.5257 differ by 0.07m. Since the cutoff is at 5m, the 0.1m is 2% of the whole range which seems suspiciously big to wave it off as a rounding difference - it is even more suspicious since there is no math involved here :wink:

**Comment by angelacmaio** [comment]
Both the reported positions and true postitions in `run.yml` and `events.yml` are recorded with respect to the world origin. [The (10.0, 0.0, 0.0) artifact origin offset is applied to the reported position](https://github.com/osrf/subt/blob/840975255690efaa16ca2d851ff8e606fc126648/subt_ign/src/GameLogicPlugin.cc#L1850) before comparing to the true artifact positions. The artifact's true position also incorporates the offset from the bottom of the artifact to the artifact localization point described in the [Artifacts Specification Guide](https://subtchallenge.com/resources/SubT_Cave_Artifacts_Specification.pdf) and implemented [here](https://github.com/osrf/subt/blob/840975255690efaa16ca2d851ff8e606fc126648/subt_ign/src/GameLogicPlugin.cc#L508).
