### ISSUE TITLE
Unexpected position of Teambase in Urban World 1

### ISSUE THREAD

**Issue by m3d** [osrf/subt#690]
I was wondering where the teambase disappeared and it was hanging in the space:
![u1-funny-teambase-placement](https://user-images.githubusercontent.com/5664353/97639971-f7f19a80-1a3f-11eb-96bd-7184d5893997.jpg)
... but maybe it is expected?
(very low priority)
robotika, 575f5c5d-588c-432e-bb54-6a0cd6a9808f

**Comment by nkoenig** [comment]
See pull request #717

**Comment by nkoenig** [comment]
This has been fixed and released.
