### ISSUE TITLE
Make tunnel circuit worlds available on cloudsim

### ISSUE THREAD

**Issue by AravindaDP** [osrf/subt#695]
It would be really nice if tunnel circuit worlds were also available to practice through cloudsim as well (Similar to urban circuit worlds)

And hope cave circuit worlds would also be available to submit for practice after the award ceremony

**Comment by m3d** [comment]
:) I was going to write the same request, but then I tested in "Tunnel Practice" worlds, dark, depressing so I postponed my question ... ;). Thanks

**Comment by AravindaDP** [comment]
Looks like they are now available. Closing this.
