### ISSUE TITLE
How to find name of marsupial child?

### ISSUE THREAD

**Issue by m3d** [osrf/subt#697]
Hello,
is there a way how to find the name of marsupial child? (it is needed for `detach` call)
We use variable names for strategy encoding and so this link is not clear from the robot's perspective.
thanks a lot
   Martin
p.s. or we would have to encode it in parents name
https://github.com/osrf/subt/wiki/api#marsupials

**Comment by m3d** [comment]
One possibility is to detect it from shared 3D position via radio - if there is some other robot within small radius on the start then it is maybe marsupial child/parent ...

**Comment by nkoenig** [comment]
You have a couple options:

1. Bake the child robot's name into your code.
2. Use the communication model.

**Comment by m3d** [comment]
It looks like that the marsupial drone can detach itself:
```
71.784000000 INFO /wait [wait.py:69(check_marsupials)] [topics: /clock, /rosout] Marsupial: /A100L/detach 
```
so it is not necessary to communicate with the parent "how to detach". OTOH on CloudSim I am not able to run it (it looks like the simulation is terminated after detach call). Is anybody using marsupials on CloudSim? Can you please confirm that it works for you?
thanks
    Martin

p.s. @nkoenig - thanks for info ... so parent does not know directly that it is carrying a child ... both hints (communicate it and extend name) works for us

**Comment by m3d** [comment]
The problem was on our side (missing one publishing module present for UGVs/breadcrumbs but missing for UAVs). So the drone finally took off: https://youtu.be/SnDr2xbqlvE
thanks
m.
