### ISSUE TITLE
CloudSim visualization menu of marsupial robots

### ISSUE THREAD

**Issue by m3d** [osrf/subt#698]
Minor detail, that when we deploy marsupial robots (Explorer R2 + SSCI X4) the menu does not expand. When you type some letters then it is updated., but the "Robots" group is still missing:
![marsupial-filtering](https://user-images.githubusercontent.com/5664353/98450873-c3b56280-2140-11eb-9f50-97ecc46607cb.jpg)

The robots names are `A100L` and `B100L`.

**Comment by vinhanguyen** [comment]
Fixed in https://github.com/osrf/subtportal/pull/165

**Comment by m3d** [comment]
> 
> 
> Fixed in [osrf/subtportal#165](https://github.com/osrf/subtportal/pull/165)

Thanks - is the "osrf/subtportal" repository publicly available? I get 404 when I click on the link.

**Comment by cameron-ridgewell** [comment]
> Thanks - is the "osrf/subtportal" repository publicly available? I get 404 when I click on the link.

That repository is private

**Comment by angelacmaio** [comment]
Fixed in osrf/subtportal#165
