### ISSUE TITLE
Missing solution1_1 output in log files

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#701]
I just submitted a solution, which outputs to terminal. I can see the output when testing on my local Cloudsim with Docker Compose:
```
solution1_1  | gcc v10.1 C++17
solution1_1  | Calling /subt/start: true
```
but I don't see it in the logs of my run on SubT Portal. The run was successful. I think this output was available before.

**Comment by nkoenig** [comment]
Output to the terminal is not capture in Cloudsim logs, unless it is through  ROS console such as ROSINFO.

**Comment by pauljurczak** [comment]
Thanks. I rewrote the code to publish `std_msgs::String` to `/robot_data_st` topic and I can see captured output now.
