### ISSUE TITLE
Will Adding a Custom Configuration to Existing Vehicles be allowed for the finals?

### ISSUE THREAD

**Issue by pauljurczak** [osrf/subt#710]
A pull request for custom configurations was stopped before the Cave Circuit (#513). Will *Adding a Custom Configuration to Existing Vehicles* as described at https://github.com/osrf/subt/wiki/Model%20Submission%20Process be allowed for the finals?

**Comment by nkoenig** [comment]
We recommend posting this competition-related question on the [SubT Challenge Community Forum](https://community.subtchallenge.com/login) so it can be addressed by DARPA.

**Comment by nkoenig** [comment]
We recommend posting this competition-related question on the [SubT Challenge Community Forum](https://community.subtchallenge.com/login) so it can be addressed by DARPA.
