### ISSUE TITLE
Permutation table for competition Cave Worlds?

### ISSUE THREAD

**Issue by m3d** [osrf/subt#711]
Hello,
is there somewhere table of which world corresponds to which in the [Showcase](https://www.youtube.com/watch?v=wv-nXkhr5Sk)? Thanks to @zwn for discovering this issue, that CloudSim `Cave Circuit 1` is actually `World 3` in the competition (Robotika got 5, 2, 5 points). What are the others?
thanks
  Martin

**Comment by m3d** [comment]
p.s. `Cave Circuit World 8` is `World 8` ;)

**Comment by AravindaDP** [comment]
It's in the competition logs email.

```
align to the following world names as described in the Cave Circuit Virtual Competition Showcase:

World 1: Fork in the Road
World 2: Glyph
World 3: T-Rex Handstand
World 4: The High Road
World 5: Uphill Battle
World 6: Five Fingers
World 7: Triple Decker
World 8: Rock and a Hard Place
```

**Comment by m3d** [comment]
You are absolutely, right! _The worlds are also defined by a different number order than those used in the Showcase. Please refer to the worlds as listed on the SubT Tech Repo when reviewing your logs_ ... so now just to match numbers and names
thanks for hint

**Comment by peci1** [comment]
cave_circuit_1 (Fork in the road)
cave_circuit_2 (Glyph)
cave_circuit_3 (T-Rex Handstand)
cave_circuit_4 (The high road)
cave_circuit_5 (Uphill Battle)
cave_circuit_6 (Five Fingers)
cave_circuit_7 (Triple Decker)
cave_circuit_8 (Rock and a Hard Place; Jeonlan cave)

**Comment by m3d** [comment]
Thanks, closing this "issue"

**Comment by m3d** [comment]
p.s. just for reference attached picture of presented worlds:
![ccc-worlds](https://user-images.githubusercontent.com/5664353/100127546-83afe880-2e7f-11eb-872e-e98905d7e277.jpg)
