### ISSUE TITLE
Can Ignition robot models be used in Airsim?

### ISSUE THREAD

**Issue by EdwinMeriaux** [osrf/subt#715]
Hi!

I legitimately did not know where to ask this question so I guess this is the best place to ask.
I would like to use the DARPA subt drone in Airsim. Does anyone know how to port them over?
I asked similar question on the Airsim Github and did no really get an answer.

**Comment by nkoenig** [comment]
I'm not familiar with how Airsim works, but you are free to use the drones. If Airsim can use SDF files, then you "should" be able to easily use the drones. Otherwise, you'll have to convert the SDF model files to the format used by Airsim.

**Comment by nkoenig** [comment]
Closing in order to triage issue tracker.
