### ISSUE TITLE
Very unrealistic physics during competition run for a falling UGV

### ISSUE THREAD

**Issue by peci1** [osrf/subt#719]
This happened to the poor X2 in competition run 07 of CTU-CRAS-NORLAB:

![physics](https://user-images.githubusercontent.com/182533/101757128-0e772100-3ad7-11eb-85e0-93393261ff65.gif)

Full resolution video here: https://vimeo.com/489336330 .

It seems some highly unrealistic forces were generated during the fall.

**Comment by rsawtell** [comment]
This appears to be very common now, we can reproduce it almost every time with the stairs in urban environment.


https://user-images.githubusercontent.com/700223/119652256-d8fb9100-bdf3-11eb-88b1-fdfa5b7a08d9.mp4

**Comment by peci1** [comment]
@rsawtell I'd check whether the inertial properties of all links are reasonable. Especially, whether the wheels have some non-negligible weight.

**Comment by rsawtell** [comment]
Looking at the CoRo_Allie sdf the wheels all have <mass>5.124</mass> and the body has <mass>26.6</mass>.

**Comment by peci1** [comment]
Okay, the inertials look good. The collision element look good, too. This is becoming strange. What was happening before? Did the robot roll down another flight of stairs before it came to the view?

We do not observe this kind of problems in any finals world with ctu_cras_norlab robots. However, we do not roll down stairs :)

**Comment by peci1** [comment]
The very newest version of gazebo (4.9.1) added a plugin for visualizing contacts. Can you use this plugin to visualize them to see whether there are any false contact points detected? You'll find the plugin in the three dot menu of the GUI...

**Comment by nkoenig** [comment]
We have updated DART to resolve this issue in this [PR](https://github.com/ignition-forks/dart/pull/28). Let me know if you still see this problem.
