### ISSUE TITLE
No RGB data for new Dome/release 2020-12-16

### ISSUE THREAD

**Issue by m3d** [osrf/subt#731]
I am testing new release 2020-12-16 (locally), primarily to check Kloubak K2 lights, but I am not getting any RGB data there. Now the same for SSCI X4 config 2 - was there some rename of topics or some other change we should be aware of? I will check it also on CloudSim to have another reference.
thanks
   Martin

**Comment by m3d** [comment]
p.s. just confirmed (robotika, `ver95artfdomecs1`, `24e784c3-4e2b-4a60-a25b-636f541a9dae`) - the drone passed backpack and did not report anything (it will be 100% when the drone returns and I will check the log files). So is it expected that the old docker image should work with the latest release?

**Comment by nkoenig** [comment]
I'm seeing RGB data with the Kloubak. Here is what I'm running:

```
ign launch competition.ign worldName:=simple_cave_01 circuit:=cave robotName1:=R1 robotConfig1:=ROBOTIKA_KLOUBAK_SENSOR_CONFIG_2
```

```
rosrun rviz rviz
```

Then I can visualize the point cloud and RGBD image.

Do you see any error messages on the console?

**Comment by m3d** [comment]
`36             rosmsg.image       0 |     0 |   0.0Hz`
i.e. no image data and the drone returned without scoring
![dome-no-point](https://user-images.githubusercontent.com/5664353/102515504-2417b800-408e-11eb-8042-b18c450a6a5f.jpg)

**Comment by m3d** [comment]
@nkoenig thanks - note that we are using docker images for the simulation and the bridge

**Comment by m3d** [comment]
when I run `rostopic list | grep image` in the robot docker image I do not see any `compressed` topic, is it expected?

**Comment by nkoenig** [comment]
The problem is the bridge docker image compiled `ros-ign` from source instead of using the debians. This cause image compression to be left out.

Fix is here: https://github.com/osrf/subt/pull/732

New docker image have been built and uploaded to cloudsim and dockerhub.

**Comment by m3d** [comment]
Great! Thanks for quick response and fix! :)
```
root@md-ThinkPad-P50:/osgar-ws# rostopic list | grep image
/A150L/front/image_raw
/A150L/front/image_raw/compressed
/A150L/front/image_raw/compressed/parameter_descriptions
/A150L/front/image_raw/compressed/parameter_updates
/A150L/front/image_raw/compressedDepth
/A150L/front/image_raw/compressedDepth/parameter_descriptions
/A150L/front/image_raw/compressedDepth/parameter_updates
/A150L/front/image_raw/theora
/A150L/front/image_raw/theora/parameter_descriptions
/A150L/front/image_raw/theora/parameter_updates
/A150L/front/optical/image_raw
```
i.e. locally I can see the `compressed` image topics and I will check it also on CloudSim.

**Comment by m3d** [comment]
now it works also on CloudSim:
![dome-scored](https://user-images.githubusercontent.com/5664353/102533987-66e58a00-40a6-11eb-8beb-5ff050d1dd18.jpg)
thanks a lot
   m.
