### ISSUE TITLE
which branch shuoud I clone?我该克隆哪个分支？

### ISSUE THREAD

**Issue by SIchenJi** [osrf/subt#747]
the website says：
 # Clone one of the circuit branches (e.g. tunnel_circuit or urban_circuit)
 git clone https://github.com/osrf/subt -b [branch_name]
but I can not find a branch with a such name:'tunnel_circuit' or 'urban_circuit'.
or I just need to clone 'master'? I really want to know what does 'tunnel_circuit' branch consist of.
网站上说克隆 tunnel_circuit 或 urban_circuit,但我并没有发现有这两个名字的分支，如果我想克隆tunnel_circuit分支，我该怎么做？

**Comment by nkoenig** [comment]
You could clone `master`. Other branches are either there for historical reasons, or are under active development.
