### ISSUE TITLE
Unable to download logs from cloudsim web interface

### ISSUE THREAD

**Issue by petrlmat** [osrf/subt#775]
Since the cloudsim update I am unable to download any logs through the web interface. After clicking on the download button and selecting the log, an Unknown error appears. See screenshot below. I was able to download logs without any problem before the update. The issue occurs in Opera Version:73.0.3856.257. I also tested with Firefox 84.0.2 with the same result.
![Screenshot from 2021-02-02 15-28-32_edit](https://user-images.githubusercontent.com/15618729/106615005-472df680-656c-11eb-8b05-e4deb98df076.png)

**Comment by nkoenig** [comment]
The CORS configuration on S3 was not setup properly. This has been fixed.
