### ISSUE TITLE
New model submission wiki page is outdated

### ISSUE THREAD

**Issue by peci1** [osrf/subt#793]
I just read [this section](https://github.com/osrf/subt/wiki/Model%20Submission%20Process#adding-a-custom-configuration-to-existing-vehicles) and it is full of outdated information:

> Custom payload configurations can be submitted as pull requests and should be composed using the vehicles (X1-X4, currently) 

> and sensors (including sensor range, resolution, and noise parameters) already available on Fuel and tabulated at the SubT API

So we can't create novel sensors without creating a whole new robot model?

> Submit a pull request to the default branch

Would you please review this part and update it according to the current state?

**Comment by angelacmaio** [comment]
Updated in [d8b4507](https://github.com/osrf/subt/wiki/Model-Submission-Process/d8b4507acd78b899e74cab1051ee8638b7d6683e). Thanks for pointing this out.
