### ISSUE TITLE
Content missing from Catkin System Setup step 6: Launch simulator

### ISSUE THREAD

**Issue by pabsan-0** [osrf/subt#794]
Hello, I've been trying to install the simulator in a Xubuntu 18.04 virtual machine

I followed the steps from https://github.com/osrf/subt/wiki/Catkin%20System%20Setup until the end and when I run the test simulation in step 6 a lot of elements are missing from the world (no robot + no cave ouside of the "house" ). Am I missing something? 

![image](https://user-images.githubusercontent.com/63670587/108391089-a13be680-7211-11eb-8ee7-cf9c77889b72.png)

**Comment by peci1** [comment]
Hi, you can try:

- calling `ign fuel download -v 4 -j 8 --type model -u "https://fuel.ignitionrobotics.org/OpenRobotics/collections/SubT Tech Repo"` to pre-download all models (the simulator sometimes has problems downloading models on the fly)
- calling `export LC_ALL=C` in the console before launching the simulator... it is still picky about the system langugage, and this command tells it to behave as if English were the system language

If neither of these helps, show us what's the console output when you launch the simulator (and how exactly you launch it).

Also, do you have an NVidia GPU available inside the virtual machine (or a similar GPU with support of OpenGL 3.3 compatibility context)?

**Comment by solder-fumes-asthma** [comment]
Hi, 

I've tried those and it still didn't work. Also switched to a virtual machine with default Ubuntu 18.04 and I have the same issue. Please find the log attached. To run the test simulation I just run these lines as shown in the tutorial: 

cd ~/subt_ws/
source ~/subt_ws/install/setup.bash
ign launch -v 4 competition.ign worldName:=tunnel_circuit_practice_01 circuit:=tunnel robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1

I have an nvidia 1060 on my computer but I am unsure whether the virtual machine can use it. I've been looking into it but can't figure it out. Could you please tell me if besides the GPU the logs & commands look good? 

Thanks.

[output_log.txt](https://github.com/osrf/subt/files/6022356/output_log.txt)

**Comment by peci1** [comment]
The log looks normal. Can you also post the contents of `~/.ignition/rendering/ogre2.log`? That would tell us whether the graphics subsystem is suitable.

Also, can you spawn two robots, add a image display in the simulator, and try looking at the other robot via a robot-mounted camera? You can try it with e.g. EXPLORER_X1_SENSOR_CONFIG_1, they have cameras in all directions. Because sometimes the GUI has some glitches but the sensor cameras have it right.

**Comment by peci1** [comment]
Also, post the output of `glxinfo` inside the container. You may need to install `mesa-utils` to get the program.

**Comment by solder-fumes-asthma** [comment]
Please find the ogre2 and glxinfo outputs attached. I will look into spawning those robots now, I'm completely new to the environment so it might take me some time.

Thanks. 

[ogre2.log](https://github.com/osrf/subt/files/6023064/ogre2.log)
[glxinfo.txt](https://github.com/osrf/subt/files/6023065/glxinfo.txt)

**Comment by peci1** [comment]
I don't see anything wrong in these logs, too. It will need a look from some Ignition Gazebo developers.

And why do you run it in a VM? Do you have a non-Linux operating system on your computer? Can't you install Ubuntu in dual boot? That could save you some headaches. An it would also improve performance of the simulator (it is slow even on bare metal). If your main system is Linux (not necessarily Ubuntu 18.04), the I' suggest you to use the Docker installation.

**Comment by solder-fumes-asthma** [comment]
I am actually running a dual boot already, however I couldn't get it to work on my linux (pop os 20.10) and since I didn't want to go for a triple boot I figured the easy way out would be using a virtual machine. Might reconsider though seeing that this isn't making it simpler...

**Comment by peci1** [comment]
Docker should work well in that case.

**Comment by nkoenig** [comment]
* Do you see any red error text appear in the console?
* Can you trying running this command, which has levels turned off:
```
ign launch -v 4 competition.ign worldName:=tunnel_circuit_practice_01 circuit:=tunnel robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1 levels:=false
```
