### ISSUE TITLE
Catkin System setup wiki: Needs a few updates

### ISSUE THREAD

**Issue by peci1** [osrf/subt#800]
I was just installing a fresh Ubuntu 18.04 system and noticed a few glitches in the https://github.com/osrf/subt/wiki/Catkin%20System%20Setup wiki.

- step 1 should also install `python-rosdep`
- somewhere between 2-4 should also be `sudo rosdep init && rosdep update`
- step 5 should also call `rosdep install --from-paths src --ignore-src -r` before building the WS
- the build command should be `catkin_make -DCMAKE_BUILD_TYPE=Release install` to be consistent with the docker images

Lower on the page, there is the ign fuel download command, which uses 16 threads. I think that's too much (you probably know better what is the best number, but it seemed to me that all `-j16` were already lowered to `-j8` in the dockers).

**Comment by pauljurczak** [comment]
Additionally, step 1 should install `git`, which doesn't come with a standard Ubuntu distribution.

**Comment by nkoenig** [comment]
Thanks, all changes have been made.

**Comment by peci1** [comment]
Thanks!
