### ISSUE TITLE
Docker: build.bash bad date format with non-english system

### ISSUE THREAD

**Issue by AndreaFinazzi** [osrf/subt#801]
In [docker/build.bash#L39](https://github.com/osrf/subt/blob/61d2e7a3df6dfefb4228247d5f67416b4f733d9a/docker/build.bash#L39), the date command
`$(date +%Y_%b_%d_%H%M)` 
could result in badly formatted tags (and `docker build` error) with non-English time formats (Korean, in our case).

We fixed with `$(date +%F_%H%M)` which involves only numerical characters.

**Comment by nkoenig** [comment]
Thanks. I put this patch in PR #802 in 3d5e50e.
