### ISSUE TITLE
PI missing a digit in model SDF files

### ISSUE THREAD

**Issue by rsawtell** [osrf/subt#804]
In many of the sdf model files pi is defined as 3.1459 rather than 3.14159.

For example the model file I have for X2 sensor config 6 lists:

```
                <lidar>
                    <scan>
                        <horizontal>
                            <!-- Resolution can't be above 16k, see
                            https://bitbucket.org/ignitionrobotics/ign-sensors/issues/8 -->
                            <samples>10000</samples>
                            <resolution>0.1</resolution>
                            <min_angle>-3.1459</min_angle>
                            <max_angle>3.1459</max_angle>
                        </horizontal>
```

a recursive grep shows this value in the following files:
CERBERUS_ANYMAL_B_SENSOR_CONFIG_1/4/model.sdf:                            <min_angle>-3.1459</min_angle>
CERBERUS_ANYMAL_B_SENSOR_CONFIG_1/4/model.sdf:                            <max_angle>3.1459</max_angle>
CERBERUS_ANYMAL_B_SENSOR_CONFIG_2/1/model.sdf:                            <min_angle>-3.1459</min_angle>
CERBERUS_ANYMAL_B_SENSOR_CONFIG_2/1/model.sdf:                            <max_angle>3.1459</max_angle>
CERBERUS_M100_SENSOR_CONFIG_1/3/model.sdf:                            <min_angle>-3.1459</min_angle>
CERBERUS_M100_SENSOR_CONFIG_1/3/model.sdf:                            <max_angle>3.1459</max_angle>
COSTAR_HUSKY_SENSOR_CONFIG_1/4/model.sdf:                            <min_angle>-3.1459</min_angle>
COSTAR_HUSKY_SENSOR_CONFIG_1/4/model.sdf:                            <max_angle>3.1459</max_angle>
COSTAR_HUSKY_SENSOR_CONFIG_2/2/model.sdf:                            <min_angle>-3.1459</min_angle>
COSTAR_HUSKY_SENSOR_CONFIG_2/2/model.sdf:                            <max_angle>3.1459</max_angle>
MARBLE_HD2_SENSOR_CONFIG_1/11/model.sdf:                            <min_angle>-3.1459</min_angle>
MARBLE_HD2_SENSOR_CONFIG_1/11/model.sdf:                            <max_angle>3.1459</max_angle>
MARBLE_HD2_SENSOR_CONFIG_2/3/model.sdf:                            <min_angle>-3.1459</min_angle>
MARBLE_HD2_SENSOR_CONFIG_2/3/model.sdf:                            <max_angle>3.1459</max_angle>
MARBLE_HUSKY_SENSOR_CONFIG_1/6/model.sdf:                            <min_angle>-3.1459</min_angle>
MARBLE_HUSKY_SENSOR_CONFIG_1/6/model.sdf:                            <max_angle>3.1459</max_angle>
MARBLE_HUSKY_SENSOR_CONFIG_2/4/model.sdf:                            <min_angle>-3.1459</min_angle>
MARBLE_HUSKY_SENSOR_CONFIG_2/4/model.sdf:                            <max_angle>3.1459</max_angle>
MARBLE_QAV500_SENSOR_CONFIG_1/6/model.sdf:                            <min_angle>-3.1459</min_angle>
MARBLE_QAV500_SENSOR_CONFIG_1/6/model.sdf:                            <max_angle>3.1459</max_angle>
SSCI_X4_SENSOR_CONFIG_1/1/model.sdf:                            <min_angle>-3.1459</min_angle>
SSCI_X4_SENSOR_CONFIG_1/1/model.sdf:                            <max_angle>3.1459</max_angle>
SSCI_X4_SENSOR_CONFIG_1/2/model.sdf:                            <min_angle>-3.1459</min_angle>
SSCI_X4_SENSOR_CONFIG_1/2/model.sdf:                            <max_angle>3.1459</max_angle>
X1 Config 3/18/model.sdf:                            <min_angle>-3.1459</min_angle>
X1 Config 3/18/model.sdf:                            <max_angle>3.1459</max_angle>
X1 Config 4/17/model.sdf:                            <min_angle>-3.1459</min_angle>
X1 Config 4/17/model.sdf:                            <max_angle>3.1459</max_angle>
X1 Config 4/18/model.sdf:                            <min_angle>-3.1459</min_angle>
X1 Config 4/18/model.sdf:                            <max_angle>3.1459</max_angle>
X1 Config 6/3/model.sdf:                            <min_angle>-3.1459</min_angle>
X1 Config 6/3/model.sdf:                            <max_angle>3.1459</max_angle>
X1 Config 7/4/model.sdf:                            <min_angle>-3.1459</min_angle>
X1 Config 7/4/model.sdf:                            <max_angle>3.1459</max_angle>
X1 Config 8/4/model.sdf:                            <min_angle>-3.1459</min_angle>
X1 Config 8/4/model.sdf:                            <max_angle>3.1459</max_angle>
X2 Config 6/12/model.sdf:                            <min_angle>-3.1459</min_angle>
X2 Config 6/12/model.sdf:                            <max_angle>3.1459</max_angle>
X2 Config 6/13/model.sdf:                            <min_angle>-3.1459</min_angle>
X2 Config 6/13/model.sdf:                            <max_angle>3.1459</max_angle>
X2 Config 6/14/model.sdf:                            <min_angle>-3.1459</min_angle>
X2 Config 6/14/model.sdf:                            <max_angle>3.1459</max_angle>
X2 Config 7/3/model.sdf:                            <min_angle>-3.1459</min_angle>
X2 Config 7/3/model.sdf:                            <max_angle>3.1459</max_angle>
X2 Config 8/3/model.sdf:                            <min_angle>-3.1459</min_angle>
X2 Config 8/3/model.sdf:                            <max_angle>3.1459</max_angle>

**Comment by nkoenig** [comment]
See pull request #828
