### ISSUE TITLE
Question: Scripted download of solutions 

### ISSUE THREAD

**Issue by meryl-spencer** [osrf/subt#835]
The wiki provides instructions for bypassing the web UI to _submit_ solutions via the REST interface ([https://github.com/osrf/subt/wiki/Cloudsim%20Submission]). Is their a way to bypass the web UI to _download_ solutions once they are run?  This would be very helpful for downloading runs with many robots.

**Comment by nkoenig** [comment]
Duplicate of #263

**Comment by nkoenig** [comment]
Closing in order to consolidate the conversation in issue #263.
