### ISSUE TITLE
Finals Practice 2 - fail to load or display parts of the world

### ISSUE THREAD

**Issue by m3d** [osrf/subt#881]
I have already seen it several times so I guess that it is not network issue on my side:
![fail-to-load-fp2](https://user-images.githubusercontent.com/5664353/113745826-f078a080-9705-11eb-8347-a29f6dd6df9f.jpg)
![fail-to-load-fp2b](https://user-images.githubusercontent.com/5664353/113745845-f5d5eb00-9705-11eb-9495-dc1de047d5e9.jpg)

**Comment by peci1** [comment]
This happened to me when viewing from a computer with a limited GPU (mainly VRAM).

**Comment by peci1** [comment]
https://gitlab.com/ignitionrobotics/web/gz3d/-/issues/3

**Comment by m3d** [comment]
@peci1 - good points, thanks. I just tested it on different machine, different browser, 32GB RAM ... outside view and that particular parts were still not loaded/drawn:
![Screenshot from 2021-04-06 19-04-34](https://user-images.githubusercontent.com/5664353/113750585-50257a80-970b-11eb-8f7d-5ddf335e86b6.png)

**Comment by peci1** [comment]
32 GB GPU RAM? because that's what was limiting in my case

**Comment by m3d** [comment]
:) sorry, then the web view is not for normal users ... no pure RAM, some ordinary GPU/Lenovo P50/P52

**Comment by peci1** [comment]
I had 2 GB shared GPU memory on the failing computer. Many people with dedicated GPUs have more (I never had a problem with a 4 GB GPU). Some kind of level-by-level loading would definitely help...

**Comment by peci1** [comment]
Or LOD support, but that's only in Edifice...

**Comment by peci1** [comment]
(or was it just in the [roadmap](https://ignitionrobotics.org/docs/all/roadmap))?

**Comment by nkoenig** [comment]
Version 13 of the model should work: https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Urban%20Stairwell%20Platform%20Centered. 

For reference, the transparency tags in the collada file were causing the problem.
