### ISSUE TITLE
X500 corrupted RGBD data

### ISSUE THREAD

**Issue by m3d** [osrf/subt#917]
Hello,
we are observing corrupted RGBD data of up/down cameras in `CTU_CRAS_NORLAB_X500_SENSOR_CONFIG_1` model. They are broken even after `set_rate` reduction. Example of sequence of depth data in Tunnel Simple 2 looks like this:
![saveX-0000](https://user-images.githubusercontent.com/5664353/118713015-c4caf900-b821-11eb-9e7d-f299da17e006.jpg)
![saveX-0001](https://user-images.githubusercontent.com/5664353/118713031-c98fad00-b821-11eb-8827-ea2c2ebd785e.jpg)
![saveX-0002](https://user-images.githubusercontent.com/5664353/118713041-cdbbca80-b821-11eb-80db-d6c250370ae1.jpg)
![saveX-0003](https://user-images.githubusercontent.com/5664353/118713094-d6140580-b821-11eb-9c63-c11c7650242b.jpg)

This corresponds to saving of `/ROBOTNAME/up_rgbd/optical/depth/image_raw`. Thanks in advance for any hint

**Comment by peci1** [comment]
was the robot rotating in yaw?

**Comment by m3d** [comment]
> was the robot rotating in yaw?

yes, but not much - should it matter?

**Comment by peci1** [comment]
Yes, it does - there is a known issue where orientation w.r.t world frame affects camera clipping: https://github.com/ignitionrobotics/ign-sensors/issues/128 .

**Comment by peci1** [comment]
A workaround is to set very high near clip distance, e.g. 0.5 m was usually enough, but the you lose depth measurements if you get closer than that...

**Comment by m3d** [comment]
Interesting, thanks for hint - I would try it tonight.

**Comment by m3d** [comment]
> A workaround is to set very high near clip distance, e.g. 0.5 m was usually enough, but the you lose depth measurements if you get closer than that...

Another stupid question - is it possible to do it on simulation side? Or do you mean to drop whole image or part of the image "once a while"? Is there some service like the newest `set_rate`??

**Comment by peci1** [comment]
This would have to be set in the SDF. If running locally, you can edit the SDF in `~/.ignition/fuel` .

**Comment by m3d** [comment]
OK, thanks - so no chance on CloudSim?

**Comment by peci1** [comment]
I think this is a regular bug so you can try submitting a fix for it.

**Comment by peci1** [comment]
Do you know what the clipped values are? Are they NaN, Inf or something else?

**Comment by m3d** [comment]
> Do you know what the clipped values are? Are they NaN, Inf or something else?

well, I have only indirect logs, as the depth is converted to 16bit millimeters and
```
>>> depth
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint16)
```
which is after
```
>>> np.clip(float('inf'), 1, 0xFFFF)
65535.0
>>> np.clip(float('-inf'), 1, 0xFFFF)
1.0
>>> np.clip(float('nan'), 1, 0xFFFF)
nan
```
and then conversion to `uint16`
```
>>> arr = np.array([float('nan')])
>>> np.ndarray.astype(arr, dtype=np.dtype('H'))
array([0], dtype=uint16)
```

So I suppose that it was `-inf` for up pointing camera.

**Comment by m3d** [comment]
@nkoenig is there a plan to fix this before the first SubT code freeze? Thanks m.

**Comment by knoedler** [comment]
#960 will fix a lot of what you are seeing with the top camera.  The camera is occluded by the visual.

**Comment by m3d** [comment]
@knoedler thanks for hope :-)

**Comment by angelacmaio** [comment]
#960 was merged

**Comment by m3d** [comment]
it was merged but not released?! (which may change today or tomorrow)

**Comment by malcolmst** [comment]
any information on when this will be released?

**Comment by malcolmst** [comment]
@angelacmaio @nkoenig sorry to be a pain about this, but whether or not #960 will be released before the upcoming submission deadline will affect my work planning significantly, so if you have any information on this it would be greatly appreciated. Thanks!

**Comment by m3d** [comment]
This issue seems to be really gone with release 2021-07-13, thank you.
