### ISSUE TITLE
MARBLE_HUSKY_SENSOR_CONFIG_5 meshes missing

### ISSUE THREAD

**Issue by dan-riley** [osrf/subt#928]
After the rename of MARBLE_HUSKY_SENSOR_CONFIG_6 to 5 today, the 'meshes' folder no longer gets created in the install folder, so RVIZ is unable to display the model correctly.  I see a previous commit deleted the meshes folder completely, and the model.sdf points to the fuel config_4 files.  But the robot_from_sdf.xacro points to package://marble_husky_sensor_config_5/meshes/*.  I have verified that changing those references to config_1 solves the issue (config_4 also does not have the meshes folder locally).

**Comment by nkoenig** [comment]
Fix has been applied.
