### ISSUE TITLE
Question: Vehicle damage effects 

### ISSUE THREAD

**Issue by meryl-spencer** [osrf/subt#937]
The latest updates have added vehicle damage. If a robot triggers the 'damaged' condition what is the effect on the robot? For example which of the following statements about damages robots are true: 

A damaged robot can move. 
A damaged robot continues to receive lidar data
A damaged robot can send and receive messages 
All ros topics associated with the damaged robot are shut down completely

**Comment by angelacmaio** [comment]
A [Collision Damage section](https://github.com/osrf/subt/wiki/api#collision-damage) has been added to the API for reference. The damage plugin represents only mechanical failure of active joints. To answer your statements about a robot's capabilities after being damaged: 

A damaged robot can move - False
A damaged robot continues to receive lidar data - True
A damaged robot can send and receive messages - True
All ros topics associated with the damaged robot are shut down completely - False
