### ISSUE TITLE
Marsupial between Karen/Mike and M100/X500 does not work

### ISSUE THREAD

**Issue by wolfgangschwab** [osrf/subt#955]
In the robots wiki the description states that **CoRo_Mike** an **Coro_Karen** can carry **X500** and **M100**. Trying this, an error message (`Invalid marsupial configuration`) is shown. 

example test command:
`./run.bash osrf/subt-virtual-testbed competition.ign worldName:=finals_qual headless:=false robotName1:=X1n1 robotConfig1:=CoRo_Mike_SENSOR_CONFIG_1 robotName2:=X4n1 robotConfig2:=CERBERUS_M100_SENSOR_CONFIG_1 marsupial1:=X1n1:X4n1 robotName3:=X3nTB robotConfig3:=TEAMBASE  circuit:=finals`

**Comment by nkoenig** [comment]
I've updated the wiki to list only `RMF`, `Pam,` and `Crystal`.
