### ISSUE TITLE
Leaky Geometry

### ISSUE THREAD

**Issue by rsawtell** [osrf/subt#961]
Our old friend lidar passing through walls is still around, lidar scan of X1 (though it's not specific to any one robot) in starting area of finals practice 1 (very zoomed out):

![image](https://user-images.githubusercontent.com/700223/122996574-03038d00-d379-11eb-90f2-aa7d1d1e7cb3.png)

**Comment by iche033** [comment]
I'm trying to reproduce this issue. I tested with 3D long range lidar from X1 C4 and 2D lidar scan from X1 C2 on finals practice 01 world and tried moving the robot around in the staging area but I couldn't reproduce the leak. Here's what I get on rviz: 

![points_leak_final](https://user-images.githubusercontent.com/4000684/124661854-eed18c80-de5c-11eb-91b7-c4e6643cf420.gif)

Let me know if I'm doing something different from you.

**Comment by rsawtell** [comment]
Looks like you are doing what I'm doing. Does the model update command not clear old models that it could be an older model on my system that is getting used in place of the newer ones? I updated everything this morning to be sure and it is still doing it for me.

**Comment by iche033** [comment]
@mjcarroll was able to reproduce the issue and spotted some visible gaps at the vents and the entrance area when viewing at certain angle. We've patched the finals staging area mesh and uploaded a new version onto Fuel.
https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Finals%20Staging%20Area
