### ISSUE TITLE
Cloudsim behavior differences at different times of day

### ISSUE THREAD

**Issue by realdealneil** [osrf/subt#963]
We have been testing on cloudsim lately and we are getting very different behavior sometimes even though we are running the exact same cloudsim images that have worked in the past.  We suspect that cloudsim behavior changes when lots of people are using it at once (which is likely the case right now since qualification deadline is approaching).  We are primarily seeing the difference in our air vehicles which are crashing at the entrance (a behavior that we can't reproduce locally).

**Comment by nkoenig** [comment]
The architecture of Cloudsim does not allow for simulation differences based on the number of people using cloudsim. We have also checked this hypothesis during prior circuit events and found no difference based on number of simulations.
