### ISSUE TITLE
Deadly trap in Finals Practice 1

### ISSUE THREAD

**Issue by m3d** [osrf/subt#972]
robotika, `e5ef74b7-333a-417b-a97d-fa724da16bc4` (still running), Finals Practice 1 ... there is "funny" trap catching Freyja from both sides ... is it expected?
![Screenshot from 2021-07-08 17-30-11](https://user-images.githubusercontent.com/5664353/124950518-c4c1cb00-e012-11eb-8ea3-d5daa612dbfe.png)

**Comment by m3d** [comment]
another view:
![Screenshot from 2021-07-08 17-31-52](https://user-images.githubusercontent.com/5664353/124950613-ddca7c00-e012-11eb-84bb-5e1e90e16327.png)

**Comment by m3d** [comment]
There was not much what to be done from the robot's point of view ...
![trapped2](https://user-images.githubusercontent.com/5664353/125208410-6b67cf00-e292-11eb-804f-855f19ec07cd.png)

**Comment by angelacmaio** [comment]
This is the Dynamic Collapse Obstacle, which is designed to deploy when a robot leaves the collapse region and block the path behind the robot (e.g., this robot may have destabilized the terrain in transit). The obstacle's trigger mechanism does not expressly prohibit a robot from being trapped if it reverses during the collapse or if the collapse is triggered by another robot. Your robot may be able to recognize signs of an impending collapse to avoid this case.

**Comment by m3d** [comment]
Just curious - how it should behave if the robot is moving backward? (Freyja is symmetric robot)

**Comment by angelacmaio** [comment]
This obstacle triggers based on a robot exiting the detection region, regardless of which direction the robot is moving. You can explore the functionality by driving a robot through the area.

**Comment by m3d** [comment]
@angelacmaio - I uploaded video https://youtu.be/FcBhwthCQtY
 ... just to demonstrate if the robot has any chance to do anything.
