### ISSUE TITLE
docker image subt_shell does not build

### ISSUE THREAD

**Issue by wolfgangschwab** [osrf/subt#984]
During build of the docker image subt_shell I got the errror: 

```
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "control_toolbox"
```

I solved it by adding 

```
# package control-toolbox is needed
RUN sudo apt-get update -qq \
 && sudo apt-get install -y -qq \
    ros-melodic-control-toolbox
```
to the Dockerfile. 
Could you please add it there too?

**Comment by peci1** [comment]
Weird, this package used to be installed automatically by the rosdep install step... Did some package remove the dependency from package.xml?

**Comment by wolfgangschwab** [comment]
I didn't have a deeper look into it. First I run the dockerfile from master branch, which did not work. Then I run the dockerfile from finals_event branch, which also did not work. Then I changed it, and the problem was solved. ;-)

**Comment by meryl-spencer** [comment]
I have the same issue

**Comment by nkoenig** [comment]
See PR #1021.
