### ISSUE TITLE
Unable to submit to prelim finals circuit

### ISSUE THREAD

**Issue by realdealneil** [osrf/subt#985]
I've tried to submit a solution to the finals prelim circuit (assuming that we can replace the submission later as we've been able to in the past).  Both times, it gave me an error: "Error #5514: Circuit rule not found."  Are we not able to submit to the prelim circuit yet?

**Comment by m3d** [comment]
I am not sure about the official name - I guessed `Finals Preliminary Round` but I also got
```
{
    "errcode": 5514,
    "msg": "Circuit rule not found.",
    "extra": null,
    "errid": "eb3492a7-b1a2-4cc2-a893-2f126837fefb",
    "route": "POST /1.0/simulations",
    "user-agent": "",
    "remote-address": "89.24.34.90"
}
```

**Comment by m3d** [comment]
p.s. I also tried manual submission and it failed as @realdealneil described:
![submission-fpr](https://user-images.githubusercontent.com/5664353/126879439-20c1e6ff-3105-4512-a3b9-e5e66067e5a9.jpg)

**Comment by m3d** [comment]
this problem still persists:
```
{
    "errcode": 5514,
    "msg": "Circuit rule not found.",
    "extra": null,
    "errid": "9e338135-624c-48c3-bc8a-4c31b0d6bb16",
    "route": "POST /1.0/simulations",
    "user-agent": "",
    "remote-address": "89.24.34.90"
}
```

**Comment by hilario** [comment]
I can confirm the same problem, maybe the submission is not open yet?

**Comment by nkoenig** [comment]
The submission should now be live.

**Comment by m3d** [comment]
I can confirm that it worked now, thanks.

**Comment by m3d** [comment]
p.s. is the time somehow limiting?
```
    "created_at": "2021-07-26T17:13:01.372845045Z",
    "updated_at": "2021-07-26T17:13:01.468182231Z",
    "valid_for": "96h0m0s",
...
```

**Comment by nkoenig** [comment]
The `valid_for` time is a bit confusing. It's the time that the simulation can run for, in real-time, before being terminated. It does not affect your submission to the prelims.

**Comment by realdealneil** [comment]
I can confirm it's working as well.  Thanks for the update.  Closing.
