### ISSUE TITLE
Describe limitations of markers sent to the mapping server

### ISSUE THREAD

**Issue by peci1** [osrf/subt#987]
I know that Ignition GUI (and probably also its web version) doesn't support all types of markers (e.g. TEXT type). Could you please explicitly list which marker types are supported?

**Comment by nkoenig** [comment]
I think you are specifically referring to the visualization during live runs. If that is correct, then I've updated the table in the wiki to indicate visualization capabilities per topic. https://github.com/osrf/subt/wiki/API#mapping-server

**Comment by peci1** [comment]
Thanks, that looks good. So if markers should not display in Ignition at all, maybe you could also add another column "RViz" with all checkmarks... Just to put there a hint that Rviz is the tool that should be used for displaying all the information.

**Comment by acschang** [comment]
I've added the RViz column into the table for the Mapping Server API.  Essentially the markers are any sort of visualizations that add context to the map data sent to the mapping server that fits within the [RViz marker API](http://wiki.ros.org/rviz/DisplayTypes/Marker).

**Comment by peci1** [comment]
Thanks!
