### ISSUE TITLE
Watch feature for "Finals Preliminary Round"?

### ISSUE THREAD

**Issue by m3d** [osrf/subt#988]
Hello,
I am curious if the new feature:
https://subtchallenge.world/watch
is going to be used in FPR or in Finals only? Or it depends on the team if they publish their FPR submission with "public" option?
thank you
   m.

**Comment by angelacmaio** [comment]
Web visualization of active runs will not be accessible for official competition simulations to preserve competition integrity. All official results must be verified by DARPA before being publicized. Results for the Preliminary Round will be released the week of August 9-13 and results for the Prize Round will be released at the Final Event on September 21-24.
