### ISSUE TITLE
Network range simulation

### ISSUE THREAD

**Issue by hilario** [osrf/subt#994]
In our local catkin simulation, the robots have permanent communication, implying no range limit. This is not true in the cloudsim simulation. How can we simulate the correct behavior? Is there any missing flag that we need to pass?

**Comment by peci1** [comment]
do you run a multimaster simulation (i.e. each robot having its own ROS_MASTER_URI)?

**Comment by hilario** [comment]
Not at all, only one ROS_MASTER from the simulator.

**Comment by peci1** [comment]
That could be the problem. Try running each pair of bridge and solution code under a different ROS master.
